import { prisma } from "@/lib/db";

export type AuditEventType =
  | "student.verification.submitted"
  | "student.verification.approved"
  | "student.verification.rejected"
  | "student.case.opened"
  | "student.case.action"
  | "student.case.submitted"
  | "student.permission.denied"
  | "educator.case.created"
  | "admin.verification.reviewed"
  // Hospital OS — see docs/ENTERPRISE_HOSPITAL_ARCHITECTURE.md §5.
  | "hospital.patient.registered"
  | "hospital.encounter.registered"
  | "hospital.encounter.updated"
  | "hospital.vital.recorded"
  | "hospital.note.created"
  | "hospital.bed.stateChanged"
  | "hospital.bed.cleaned"
  | "hospital.admission.created"
  | "hospital.admission.transferred"
  | "hospital.discharge.initiated"
  | "hospital.discharge.finalized"
  | "hospital.medication.ordered"
  | "hospital.medication.administered"
  | "hospital.lab.ordered"
  | "hospital.lab.resultReleased"
  | "hospital.lab.criticalResultAcknowledged"
  | "hospital.imaging.ordered"
  | "hospital.imaging.reportEntered"
  | "hospital.imaging.criticalReportVerified"
  | "hospital.billing.chargeCreated"
  // Phase 1 — Unified Clinical Core. Named to match the target event
  // catalog in docs/EVENT_ARCHITECTURE.md §4 (PATIENT_CREATED-style),
  // recorded today via the existing synchronous AuditEvent mechanism, not
  // a new event bus — see docs/CLINICAL_CORE.md §6.
  | "hospital.patient.created"
  | "hospital.patient.updated"
  | "hospital.patient.merged"
  | "hospital.patient.viewed"
  // Phase 6.8 — EMPI identity mutations.
  | "hospital.patient.unmerged"
  | "hospital.patient.identifierAdded"
  | "hospital.patient.emergencyContactAdded"
  | "hospital.patient.deceasedRecorded"
  | "hospital.encounter.cancelled"
  | "hospital.diagnosis.added"
  | "hospital.problem.added"
  | "hospital.allergy.added"
  | "hospital.episode.created"
  | "hospital.episode.closed"
  | "hospital.task.created"
  | "hospital.task.completed"
  | "hospital.document.created"
  | "hospital.document.versioned"
  | "hospital.consent.recorded"
  | "hospital.consent.revoked"
  | "hospital.referral.created"
  | "hospital.referral.updated"
  | "patient.account.registered"
  // Phase 2 — Patient Flow / ADT. Named to match the brief §59 event
  // catalog; recorded through the same synchronous AuditEvent mechanism
  // (docs/EVENT_ARCHITECTURE.md — no new event bus this phase either).
  | "hospital.appointment.created"
  | "hospital.appointment.cancelled"
  | "hospital.appointment.noShow"
  | "hospital.appointment.checkedIn"
  | "hospital.queue.entered"
  | "hospital.queue.priorityChanged"
  | "hospital.queue.called"
  | "hospital.queue.completed"
  | "hospital.triage.recorded"
  | "hospital.consultation.started"
  | "hospital.consultation.completed"
  | "hospital.admissionRequest.created"
  | "hospital.admissionRequest.bedReserved"
  | "hospital.admissionRequest.confirmed"
  | "hospital.admissionRequest.rejected"
  | "hospital.admissionRequest.cancelled"
  | "hospital.transferRequest.created"
  | "hospital.transferRequest.accepted"
  | "hospital.transferRequest.bedReserved"
  | "hospital.transferRequest.completed"
  | "hospital.transferRequest.cancelled"
  | "hospital.discharge.blockerChanged"
  | "hospital.discharge.expectedDateChanged"
  | "hospital.location.assigned"
  // Phase 3 — Doctor OS / Nursing OS / Medication Lifecycle / Pharmacy.
  // Recorded through the same synchronous AuditEvent mechanism as every
  // prior phase — no new event bus (brief §34/§27).
  | "hospital.note.signed"
  | "hospital.note.amended"
  | "hospital.order.created"
  | "hospital.order.cancelled"
  | "hospital.order.discontinued"
  | "hospital.medication.statusChanged"
  | "hospital.medication.verified"
  | "hospital.medication.rejected"
  | "hospital.medication.held"
  | "hospital.medication.clarificationRequested"
  | "hospital.medication.dispensed"
  | "hospital.medication.cancelled"
  | "hospital.medication.discontinued"
  | "hospital.medication.refused"
  | "hospital.medication.missed"
  | "hospital.medication.safetyOverridden"
  | "hospital.medication.reconciled"
  | "hospital.nursing.assignmentChanged"
  | "hospital.task.skipped"
  | "hospital.handoff.created"
  | "hospital.handoff.acknowledged"
  | "hospital.carePlan.created"
  | "hospital.carePlan.closed"
  | "hospital.consult.accepted"
  | "hospital.consult.completed"
  | "hospital.vital.abnormalDetected"
  // Phase 4 Milestone B — Laboratory core workflow (specimen lifecycle +
  // structured result entry/verification/amendment). Recorded through the
  // same synchronous AuditEvent mechanism as every prior phase.
  | "hospital.lab.specimenCollected"
  | "hospital.lab.specimenReceived"
  | "hospital.lab.specimenAccepted"
  | "hospital.lab.specimenRejected"
  | "hospital.lab.specimenRecollected"
  | "hospital.lab.resultEntered"
  | "hospital.lab.resultVerified"
  | "hospital.lab.resultAmended"
  // Phase 4 Milestone C — Radiology core workflow (study scheduling/
  // execution + structured report entry/verification/acknowledgement/
  // amendment). Recorded through the same synchronous AuditEvent
  // mechanism as every prior phase.
  | "hospital.imaging.scheduled"
  | "hospital.imaging.rescheduled"
  | "hospital.imaging.studyCancelled"
  | "hospital.imaging.studyCheckedIn"
  | "hospital.imaging.studyStarted"
  | "hospital.imaging.studyCompleted"
  | "hospital.imaging.reportVerified"
  | "hospital.imaging.criticalFindingAcknowledged"
  | "hospital.imaging.reportAmended"
  // Phase 5 — Billing + Insurance + Revenue Cycle. Recorded through the
  // same synchronous AuditEvent mechanism as every prior phase.
  | "hospital.billing.chargeVoided"
  | "hospital.billing.tariffCreated"
  | "hospital.billing.tariffDeactivated"
  | "hospital.billing.packageCreated"
  | "hospital.billing.packageApplied"
  | "hospital.invoice.drafted"
  | "hospital.invoice.lineAdded"
  | "hospital.invoice.issued"
  | "hospital.invoice.voided"
  | "hospital.payment.recorded"
  | "hospital.payment.allocated"
  | "hospital.payment.voided"
  | "hospital.refund.requested"
  | "hospital.refund.approved"
  | "hospital.refund.rejected"
  | "hospital.refund.completed"
  | "hospital.adjustment.created"
  | "hospital.adjustment.approved"
  | "hospital.adjustment.rejected"
  | "hospital.insurance.payerCreated"
  | "hospital.insurance.payerPlanCreated"
  | "hospital.insurance.coverageAdded"
  | "hospital.insurance.coverageDeactivated"
  | "hospital.insurance.preauthRequested"
  | "hospital.insurance.preauthDecided"
  | "hospital.claim.created"
  | "hospital.claim.submitted"
  | "hospital.claim.decided"
  | "hospital.claim.settled"
  | "hospital.claim.closed"

  // Phase 6A — Inventory + Procurement Foundation.
  | "hospital.inventory.itemCreated"
  | "hospital.inventory.itemUpdated"
  | "hospital.inventory.locationCreated"
  | "hospital.inventory.locationUpdated"
  | "hospital.inventory.stockReceived"
  | "hospital.inventory.stockIssued"
  | "hospital.inventory.stockReserved"
  | "hospital.inventory.stockReservationReleased"
  | "hospital.inventory.stockTransferred"
  | "hospital.inventory.transferReceived"
  | "hospital.inventory.transferCancelled"
  | "hospital.inventory.stockAdjusted"
  | "hospital.inventory.adjustmentApproved"
  | "hospital.inventory.adjustmentRejected"
  | "hospital.inventory.wasteRecorded"
  | "hospital.inventory.wasteApproved"
  | "hospital.inventory.lotQuarantined"
  | "hospital.inventory.lotReleased"
  | "hospital.inventory.stocktakeStarted"
  | "hospital.inventory.stocktakeCompleted"
  | "hospital.inventory.medicationLinked"
  | "hospital.procurement.supplierCreated"
  | "hospital.procurement.supplierUpdated"
  | "hospital.procurement.requisitionSubmitted"
  | "hospital.procurement.requisitionApproved"
  | "hospital.procurement.requisitionRejected"
  | "hospital.procurement.requisitionCancelled"
  | "hospital.procurement.poCreated"
  | "hospital.procurement.poSubmitted"
  | "hospital.procurement.poApproved"
  | "hospital.procurement.poCancelled"
  | "hospital.procurement.poClosed"
  | "hospital.procurement.goodsReceiptRecorded"
  | "hospital.procurement.goodsReceiptApproved"
  | "hospital.procurement.goodsReceiptRejected"
  // Phase 6.7 — Nursing Core (see docs/PHASE_6_7_NURSING.md).
  | "hospital.io.recorded"
  | "hospital.nursing.assessmentCreated"
  | "hospital.nursing.assessmentCompleted"
  | "hospital.nursing.assessmentSigned"
  | "hospital.nursing.assessmentAmended"
  | "hospital.carePlan.interventionCreated"
  | "hospital.carePlan.interventionCompleted"
  // Phase B1 — ICU Foundation.
  | "hospital.icu.unitConfigured"
  | "hospital.icu.admitted"
  | "hospital.icu.transferred"
  | "hospital.icu.observationRecorded"
  | "hospital.icu.deviceRecorded"
  | "hospital.icu.deviceStatusChanged"
  | "hospital.icu.infusionRecorded"
  | "hospital.icu.infusionStatusChanged"
  // Phase B3 — Operating Theatre & Surgical Workflow.
  | "hospital.ot.theatreConfigured"
  | "hospital.ot.procedureConfigured"
  | "hospital.ot.surgeryRequested"
  | "hospital.ot.surgeryStatusChanged"
  | "hospital.ot.surgeryScheduled"
  | "hospital.ot.surgeryScheduleCancelled"
  | "hospital.ot.checklistUpdated"
  | "hospital.ot.anesthesiaRecorded"
  | "hospital.ot.procedureStarted"
  | "hospital.ot.procedureCompleted"
  | "hospital.ot.specimenCollected"
  | "hospital.ot.implantRecorded"
  | "hospital.ot.consumableRecorded"
  | "hospital.ot.recoveryUpdated"
  // Phase B4 — Blood Bank & Transfusion Management.
  | "hospital.blood.productConfigured"
  | "hospital.blood.unitRegistered"
  | "hospital.blood.unitReleased"
  | "hospital.blood.unitQuarantined"
  | "hospital.blood.unitRecalled"
  | "hospital.blood.unitWasted"
  | "hospital.blood.typingRecorded"
  | "hospital.blood.requestCreated"
  | "hospital.blood.requestStatusChanged"
  | "hospital.blood.emergencyReleaseAuthorized"
  | "hospital.blood.compatibilityRecorded"
  | "hospital.blood.compatibilityVerified"
  | "hospital.blood.unitsReserved"
  | "hospital.blood.reservationReleased"
  | "hospital.blood.unitIssued"
  | "hospital.blood.unitDispatched"
  | "hospital.blood.unitReceived"
  | "hospital.blood.unitReturned"
  | "hospital.blood.transfusionStarted"
  | "hospital.blood.transfusionObservationRecorded"
  | "hospital.blood.transfusionStatusChanged"
  | "hospital.blood.transfusionCompleted"
  | "hospital.blood.reactionReported"
  | "hospital.blood.reactionStatusChanged"
  // Phase B5 — Emergency Department.
  | "hospital.ed.arrival"
  | "hospital.ed.locationAssigned"
  | "hospital.ed.locationReleased"
  | "hospital.ed.reassessment"
  | "hospital.ed.resuscitationActivated"
  | "hospital.ed.resuscitationUpdated"
  | "hospital.ed.disposition"
  // Phase B6 — Enterprise Pharmacy & Medication Supply Chain.
  | "hospital.pharmacy.masterUpdated"
  | "hospital.pharmacy.formularyChanged"
  | "hospital.pharmacy.dispensed"
  | "hospital.pharmacy.substitution"
  | "hospital.pharmacy.returnCreated"
  | "hospital.pharmacy.returnClassified"
  | "hospital.pharmacy.controlledWastage"
  | "hospital.pharmacy.quarantined"
  | "hospital.pharmacy.quarantineReleased"
  | "hospital.pharmacy.recallCreated"
  | "hospital.pharmacy.recallClosed"
  | "hospital.pharmacy.storageCheck"
  | "hospital.pharmacy.requestCreated"
  | "hospital.pharmacy.requestUpdated"
  | "hospital.pharmacy.transfer"
  // Phase B7 — Advanced Diagnostics (LIS quality management + PACS boundary).
  | "hospital.lab.specimenIdentitySet"
  | "hospital.lab.qcRecorded"
  | "hospital.lab.qcReviewed"
  | "hospital.lab.calibrationRecorded"
  | "hospital.lab.calibrationReviewed"
  | "hospital.lab.externalReferralCreated"
  | "hospital.lab.externalReferralUpdated"
  | "hospital.imaging.acquisitionRecorded"
  // Phase B8 — Enterprise Inventory + Procurement Depth.
  | "hospital.inventory.deptRequestCreated"
  | "hospital.inventory.deptRequestUpdated"
  | "hospital.inventory.serialRegistered"
  | "hospital.inventory.serialUpdated"
  | "hospital.procurement.contractCreated"
  | "hospital.procurement.contractDeactivated"
  | "hospital.procurement.rfqCreated"
  | "hospital.procurement.rfqUpdated"
  | "hospital.procurement.quotationRecorded"
  | "hospital.procurement.supplierSelected"
  | "hospital.procurement.invoiceRecorded"
  | "hospital.procurement.invoiceReviewed"
  // Phase B9 — Hospital Operations Layer.
  | "hospital.ops.housekeepingCreated"
  | "hospital.ops.housekeepingUpdated"
  | "hospital.ops.dietOrderCreated"
  | "hospital.ops.dietOrderUpdated"
  | "hospital.ops.mealPlanned"
  | "hospital.ops.mealUpdated"
  | "hospital.ops.transportCreated"
  | "hospital.ops.transportUpdated"
  | "hospital.ops.ambulanceCreated"
  | "hospital.ops.ambulanceStatusChanged"
  | "hospital.ops.ambulanceTripCreated"
  | "hospital.ops.ambulanceDispatched"
  | "hospital.ops.ambulanceTripUpdated"
  | "hospital.ops.maintenanceCreated"
  | "hospital.ops.maintenanceUpdated"
  | "hospital.ops.preventiveScheduled"
  | "hospital.ops.preventiveCompleted"
  | "hospital.ops.downtimeStarted"
  | "hospital.ops.downtimeEnded"
  | "hospital.ops.equipmentCreated"
  | "hospital.ops.equipmentStatusChanged"
  | "hospital.ops.calibrationRecorded"
  | "hospital.ops.biomedMaintenanceRecorded"
  | "hospital.ops.equipmentMoved"
  | "hospital.ops.infectionReported"
  | "hospital.ops.infectionUpdated"
  | "hospital.ops.infectionInvestigationCreated"
  | "hospital.ops.exposureRecorded"
  // Phase B10 — Quality / Patient Safety.
  | "hospital.quality.incidentReported"
  | "hospital.quality.incidentTriaged"
  | "hospital.quality.incidentInvestigationStarted"
  | "hospital.quality.incidentActionRequired"
  | "hospital.quality.incidentResolved"
  | "hospital.quality.incidentClosed"
  | "hospital.quality.incidentCancelled"
  | "hospital.quality.incidentUpdated"
  | "hospital.quality.incidentReopened"
  | "hospital.quality.rcaCreated"
  | "hospital.quality.rcaReviewed"
  | "hospital.quality.capaCreated"
  | "hospital.quality.capaCompleted"
  | "hospital.quality.capaVerified"
  | "hospital.quality.capaClosed"
  | "hospital.quality.capaUpdated"
  | "hospital.quality.standardCreated"
  | "hospital.quality.measureCreated"
  | "hospital.quality.measureReviewed"
  | "hospital.quality.evidenceAttached"
  | "hospital.quality.auditCreated"
  | "hospital.quality.auditCompleted"
  | "hospital.quality.auditUpdated"
  | "hospital.quality.findingCreated"
  | "hospital.quality.findingClosed"
  // Phase B10 — Workforce / Credentialing / Privileges.
  | "hospital.workforce.assignmentCreated"
  | "hospital.workforce.assignmentEnded"
  | "hospital.workforce.availabilityChanged"
  | "hospital.workforce.shiftCreated"
  | "hospital.workforce.shiftCancelled"
  | "hospital.workforce.requirementCreated"
  | "hospital.workforce.credentialCreated"
  | "hospital.workforce.credentialVerified"
  | "hospital.workforce.credentialSuspended"
  | "hospital.workforce.credentialRevoked"
  | "hospital.workforce.privilegeGranted"
  | "hospital.workforce.privilegeSuspended"
  | "hospital.workforce.privilegeRevoked";

export interface AuditEventContext {
  facilityId?: string;
  patientId?: string;
  encounterId?: string;
}

export async function recordAuditEvent(
  type: AuditEventType,
  userId: string | null,
  detail?: Record<string, unknown>,
  context?: AuditEventContext
) {
  await prisma.auditEvent.create({
    data: {
      type,
      userId: userId ?? undefined,
      detail: detail ? JSON.parse(JSON.stringify(detail)) : undefined,
      facilityId: context?.facilityId,
      patientId: context?.patientId,
      encounterId: context?.encounterId,
    },
  });
}
