// Source: National List of Essential Medicines (NLEM) 2022, Ministry of Health and
// Family Welfare, Government of India. Generic medicine names only, alphabetized.
export const ESSENTIAL_MEDICINES: string[] = [
  "5-aminosalicylic acid (Mesalazine/Mesalaine)",
  "5-Fluorouracil",
  "6-Mercaptopurine",
  "Abacavir",
  "Abacavir (A) + Lamivudine (B)",
  "Acetazolamide",
  "Acetylsalicylic acid",
  "Actinomycin D",
  "Activated Charcoal",
  "Acyclovir",
  "Adenosine",
  "Adrenaline",
  "Albendazole",
  "All-trans retinoic acid",
  "Allopurinol",
  "Alprostadil",
  "Amikacin",
  "Amiodarone",
  "Amitriptyline",
  "Amlodipine",
  "Amoxicillin",
  "Amoxicillin (A) + Clavulanic acid (B)",
  "Amphotericin B",
  "Ampicillin",
  "Anti-D immunoglobulin",
  "Anti-rabies immunoglobulin",
  "Anti-tetanus immunoglobulin",
  "Arsenic trioxide",
  "Artemether (A) + Lumefantrine (B)",
  "Artesunate",
  "Artesunate (A) + Sulphadoxine Pyrimethamine (B)",
  "Ascorbic acid (Vitamin C)",
  "Atazanavir (A) + Ritonavir (B)",
  "Atorvastatin",
  "Atracurium",
  "Atropine",
  "Azathioprine",
  "Azithromycin",
  "Baclofen",
  "Barium sulphate",
  "BCG vaccine",
  "Bedaquiline",
  "Bendamustine Hydrochloride",
  "Benzathine benzylpenicillin",
  "Benzoyl peroxide",
  "Benzylpenicillin",
  "Betamethasone",
  "Betamethasone (valerate)",
  "Bicalutamide",
  "Bisacodyl",
  "Bleomycin",
  "Bortezomib",
  "Budesonide",
  "Budesonide (A) +Formoterol (B)",
  "Bupivacaine",
  "Buprenorphine",
  "Buprenorphine (A) + Naloxone (B)",
  "Caffeine",
  "Calamine",
  "Calcium carbonate",
  "Calcium folinate",
  "Calcium gluconate",
  "Capecitabine",
  "Carbamazepine",
  "Carbimazole",
  "Carboplatin",
  "Carboxymethyl cellulose",
  "Cefadroxil",
  "Cefazolin",
  "Cefixime",
  "Cefotaxime",
  "Ceftazidime",
  "Ceftriaxone",
  "Cefuroxime",
  "Cetirizine",
  "Chlorambucil",
  "Chlorhexidine",
  "Chloroquine",
  "Cholecalciferol",
  "Ciprofloxacin",
  "Cisplatin",
  "Clarithromycin",
  "Clindamycin",
  "Clobazam",
  "Clofazimine",
  "Clomiphene citrate",
  "Clomipramine",
  "Clonazepam",
  "Clopidogrel",
  "Clotrimazole",
  "Cloxacillin",
  "Clozapine",
  "Co-trimoxazole [Sulphamethoxazole (A) + Trimethoprim (B)]",
  "Coagulation factor IX",
  "Coagulation factor VIII",
  "Coal tar (A) + Salicylic Acid (B)",
  "Colchicine",
  "Condom",
  "Cryoprecipitate",
  "Cyclophosphamide",
  "Cycloserine",
  "Cyclosporine",
  "Cytosine arabinoside",
  "D- Penicillamine",
  "Dabigatran",
  "Dacarbazine",
  "Daclatasvir",
  "Dapsone",
  "Darunavir",
  "Darunavir (A) + Ritonavir (B)",
  "Daunorubicin",
  "Delamanid",
  "Desferrioxamine",
  "Dexamethasone",
  "Dextran-40",
  "Diazepam",
  "Diclofenac",
  "Dicyclomine",
  "Diethylcarbamazine",
  "Digoxin",
  "Diltiazem",
  "Dinoprostone",
  "Diphtheria antitoxin",
  "Dobutamine",
  "Docetaxel",
  "Dolutegravir",
  "Domperidone",
  "Donepezil",
  "Dopamine",
  "Doxorubicin",
  "Doxycycline",
  "DPT vaccine",
  "DPT+ Hib+ Hep B vaccine",
  "Efavirenz",
  "Enalapril",
  "Enoxaparin",
  "Entecavir",
  "Erythropoietin",
  "Escitalopram",
  "Esmolol",
  "Ethambutol",
  "Ethinylestradiol (A) + Levonorgestrel (B)",
  "Ethionamide",
  "Ethyl alcohol (Denatured)",
  "Etoposide",
  "Fentanyl",
  "Ferrous salts",
  "Ferrous Salts (A) + Folic Acid (B)",
  "Filgrastim",
  "Fluconazole",
  "Fludrocortisone",
  "Flunarizine",
  "Fluorescein",
  "Fluoxetine",
  "Fluphenazine",
  "Folic Acid",
  "Framycetin",
  "Fresh frozen plasma",
  "Furosemide",
  "Fusidic acid",
  "Gadobenate dimeglumine",
  "Gefitinib",
  "Gemcitabine",
  "Gentamicin",
  "Glimepiride",
  "Glucose",
  "Glucose(A) + Sodium chloride (B)",
  "Glutaraldehyde",
  "Glycerin",
  "Glyceryl trinitrate",
  "Glycopyrrolate",
  "Griseofulvin",
  "Haemodialysis fluid",
  "Haloperidol",
  "Halothane",
  "Heparin",
  "Hepatitis B immunoglobulin",
  "Hepatitis B vaccine",
  "Homatropine",
  "Hormone releasing IUD",
  "Human chorionic gonadotropin",
  "Human normal immunoglobulin",
  "Hydrochlorothiazide",
  "Hydrocortisone",
  "Hydrogen Peroxide",
  "Hydroxocobalamine",
  "Hydroxychloroquine",
  "Hydroxypropyl methylcellulose",
  "Hydroxyurea",
  "Hyoscine butylbromide",
  "Ibuprofen",
  "Ifosfamide",
  "Imatinib",
  "Insulin (Soluble)",
  "Insulin Glargine",
  "Insulin Intermediate Acting (NPH)",
  "Insulin Premix Injection 30:70 (Regular : NPH)",
  "Iohexol",
  "Ipratropium",
  "Irinotecan HCI Trihydrate",
  "Iron sucrose",
  "Isoflurane",
  "Isoniazid",
  "Isosorbide dinitrate",
  "Ispaghula",
  "Itraconazole",
  "IUD containing Copper",
  "Ivermectin",
  "Japanese Encephalitis Vaccine",
  "Ketamine",
  "L-Asparaginase",
  "Labetalol",
  "Lactulose",
  "Lamivudine",
  "Latanoprost",
  "Lenalidomide",
  "Letrozole",
  "Leuprolide acetate",
  "Levetiracetam",
  "Levodopa (A) + Carbidopa (B)",
  "Levofloxacin",
  "Levonorgestrel",
  "Levothyroxine",
  "Lignocaine",
  "Lignocaine (A) + Adrenaline (B)",
  "Linezolid",
  "Lithium",
  "Loperamide",
  "Lopinavir (A) + Ritonavir (B)",
  "Lorazepam",
  "Magnesium sulphate",
  "Mannitol",
  "Measles vaccine",
  "Mebendazole",
  "Medroxyprogesterone acetate",
  "Mefenamic acid",
  "Mefloquine",
  "Meglumine diatrizoate",
  "Melphalan",
  "Meropenem",
  "Mesna",
  "Metformin",
  "Methotrexate",
  "Methylergometrine",
  "Methylprednisolone",
  "Methylrosanilinium chloride (Gentian Violet)",
  "Methylthioninium chloride (Methylene blue)",
  "Metoclopramide",
  "Metoprolol",
  "Metronidazole",
  "Midazolam",
  "Mifepristone",
  "Miltefosine",
  "Misoprostol",
  "Montelukast",
  "Morphine",
  "Moxifloxacin",
  "Mupirocin",
  "Mycophenolate mofetil",
  "N-acetylcysteine",
  "Naloxone",
  "Natamycin",
  "Neostigmine",
  "Nevirapine",
  "Nicotine replacement therapy (NRT)",
  "Nifedipine",
  "Nitrofurantoin",
  "Nitrous oxide",
  "Noradrenaline",
  "Norethisterone",
  "Nystatin",
  "Omeprazole",
  "Ondansetron",
  "Oral poliomyelitis vaccine",
  "Oral rehydration salts",
  "Ormeloxifene (Centchroman)",
  "Oxaliplatin",
  "Oxygen",
  "Oxytocin",
  "Paclitaxel",
  "Pantoprazole",
  "Para- aminosalicylic acid",
  "Paracetamol",
  "Paromomycin",
  "Peritoneal dialysis solution",
  "Permethrin",
  "Pheniramine",
  "Phenobarbitone",
  "Phenoxymethyl penicillin",
  "Phenylephrine",
  "Phenytoin",
  "Phytomenadione(Vitamin K1)",
  "Pilocarpine",
  "Piperacillin (A) + Tazobactam (B)*",
  "Platelet rich plasma/ Platelet concentrates",
  "Podophyllin resin",
  "Potassium chloride",
  "Potassium permanganate",
  "Povidone iodine",
  "Pralidoxime chloride (2-PAM)",
  "Praziquantel",
  "Prednisolone",
  "Primaquine",
  "Procaine Benzylpenicillin",
  "Proparacaine",
  "Propofol",
  "Propranolol",
  "Protamine Sulphate",
  "Pyrazinamide",
  "Pyridoxine",
  "Quinine",
  "Rabies vaccine",
  "Raltegravir",
  "Ramipril",
  "Red blood cells/ Packed RBCs",
  "Ribavirin",
  "Riboflavin",
  "Rifampicin",
  "Ringer lactate",
  "Risperidone",
  "Ritonavir",
  "Rituximab",
  "Rotavirus vaccine",
  "Salbutamol",
  "Salicylic acid",
  "Sevoflurane",
  "Silver sulphadiazine",
  "Snake Venom Antiserum",
  "Sodium bicarbonate",
  "Sodium chloride",
  "Sodium nitrite",
  "Sodium nitroprusside",
  "Sodium thiosulphate",
  "Sodium Valproate",
  "Sofosbuvir",
  "Somatostatin",
  "Spironolactone",
  "Streptokinase",
  "Streptomycin",
  "Succinylcholine",
  "Sulfasalazine",
  "Sumatriptan",
  "Surfactant",
  "Tacrolimus",
  "Tamoxifen",
  "Telmisartan",
  "Temozolomide",
  "Tenecteplase",
  "Teneligliptin",
  "Tenofovir (A) + Lamivudine (B)",
  "Tenofovir (A) + Lamivudine (B) + Dolutegravir (C)",
  "Tenofovir (A) + Lamivudine (B) + Efavirenz (C)",
  "Tenofovir Alafenamide Fumarate (TAF)",
  "Tenofovir Disproxil Fumarate (TDF)",
  "Terbinafine",
  "Tetanus toxoid",
  "Thalidomide",
  "Thiamine",
  "Thiopentone",
  "Timolol",
  "Tiotropium",
  "Tramadol",
  "Tranexamic acid",
  "Trastuzumab",
  "Trihexyphenidyl",
  "Tropicamide",
  "Tuberculin, Purified Protein derivative",
  "Valganciclovir",
  "Vancomycin",
  "Vecuronium",
  "Verapamil",
  "Vinblastine",
  "Vincristine",
  "Vitamin A",
  "Warfarin",
  "Water for Injection",
  "Whole blood",
  "Xylometazoline",
  "Zidovudine",
];

// The 27 therapeutic categories NLEM 2022 organizes medicines into.
export const NLEM_CATEGORIES: string[] = [
  "Medicines used in Anaesthesia",
  "Analgesics, Antipyretics, NSAIDs, Gout and Rheumatoid Disorder Agents",
  "Antiallergics and Medicines used in Anaphylaxis",
  "Antidotes and Substances used in Management of Poisonings/Envenomation",
  "Medicines used in Neurological Disorders",
  "Anti-infective Medicines",
  "Anti-cancer Agents, Immunosuppressives, and Palliative Care Medicines",
  "Medicines affecting Blood",
  "Blood Products and Plasma Substitutes",
  "Cardiovascular Medicines",
  "Dermatological Medicines (Topical)",
  "Diagnostic Agents",
  "Dialysis Components (Haemodialysis and Peritoneal Dialysis)",
  "Antiseptics and Disinfectants",
  "Diuretics",
  "Ear, Nose and Throat Medicines",
  "Gastrointestinal Medicines",
  "Hormones, other Endocrine Medicines and Contraceptives",
  "Immunologicals",
  "Medicines for Neonatal Care",
  "Ophthalmological Medicines",
  "Oxytocics and Antioxytocics",
  "Medicines used in treatment of Psychiatric Disorders",
  "Medicines acting on the Respiratory Tract",
  "Solutions correcting Water, Electrolyte, and Acid-base Disturbances",
  "Vitamins and Minerals",
  "Medicines for COVID-19 Management",
];
