import type { CaseDef } from "../builder";

export const cardioRespiratoryCases: CaseDef[] = [
  {
    slug: "EDU-CARD-001",
    title: "Crushing Central Chest Pain in a 58-Year-Old",
    specialty: "Cardiology",
    difficulty: "INTERMEDIATE",
    acuity: "EMERGENCY",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "male",
    patientAgeBand: "55-59",
    patientAgeExact: 58,
    chiefComplaint: "Severe central chest pain for 45 minutes",
    learningObjectives: [
      "Recognize STEMI on history, exam and ECG",
      "Sequence time-critical reperfusion decisions",
      "Identify contraindications to thrombolysis",
    ],
    presentation:
      "A 58-year-old man presents to the emergency department with severe central chest pain that started 45 minutes ago while climbing stairs.",
    initialVitals: { hr: 108, sbp: 96, dbp: 62, rr: 22, spo2: 94, tempC: 36.9, gcs: 15, status: "concern", label: "On arrival" },
    vitalsTimeline: [
      { hr: 108, sbp: 96, dbp: 62, rr: 22, spo2: 94, tempC: 36.9, gcs: 15, status: "concern", label: "On arrival" },
      { hr: 122, sbp: 84, dbp: 54, rr: 26, spo2: 91, tempC: 36.9, gcs: 15, status: "critical", label: "T+15 min (if reperfusion delayed)" },
    ],
    history: [
      { q: "Where exactly is the pain?", category: "presenting-complaint", a: "Central chest, like a heavy weight on it.", key: true },
      { q: "Does the pain radiate anywhere?", category: "presenting-complaint", a: "Yes, into my left arm and jaw.", key: true },
      { q: "Any sweating or nausea?", category: "associated-symptoms", a: "Yes, I've been sweating a lot and feel sick.", key: true },
      { q: "Any breathlessness?", category: "associated-symptoms", a: "A little, yes." },
      { q: "Do you have diabetes or high blood pressure?", category: "past-medical", a: "I have high blood pressure and high cholesterol.", key: true },
      { q: "Do you smoke?", category: "social", a: "Yes, about a pack a day for 30 years.", key: true },
      { q: "Any family history of heart disease?", category: "family", a: "My father had a heart attack at 55." },
      { q: "Any current medications?", category: "medications", a: "Amlodipine and atorvastatin." },
      { q: "Any allergies?", category: "allergies", a: "None that I know of." },
    ],
    exam: [
      { system: "general", finding: "Diaphoretic, anxious, clutching chest.", key: true },
      { system: "cardiovascular", finding: "Heart sounds normal, no murmurs, no rubs.", key: true },
      { system: "respiratory", finding: "Bilateral air entry, mild bibasal crackles." },
      { system: "vitals", finding: "Tachycardic, borderline hypotensive, tachypneic." },
    ],
    investigations: [
      { name: "12-lead ECG", category: "ecg", indication: "Suspected ACS", turnaround: 2, result: "ST elevation >2mm in leads V2-V4, reciprocal depression in II, III, aVF.", interpretation: "Anterior STEMI.", diagnostic: true },
      { name: "Troponin I", category: "biochemistry", indication: "Suspected MI", turnaround: 45, result: "0.8 ng/mL (elevated).", interpretation: "Myocardial injury confirmed, but do not wait for this before activating the cath lab.", diagnostic: true },
      { name: "Chest X-ray", category: "xray", indication: "Rule out other causes of chest pain", turnaround: 20, result: "No widened mediastinum, no pneumothorax.", interpretation: "Effectively excludes aortic dissection/pneumothorax as alternative causes." },
      { name: "D-dimer", category: "biochemistry", indication: "Low pretest probability PE screen", turnaround: 40, result: "Not indicated — high pretest probability of ACS.", interpretation: "Ordering this delays reperfusion and adds no value here.", distractor: true },
    ],
    redFlags: ["Hemodynamic instability", "ST elevation on ECG", "Radiating pain with diaphoresis"],
    referenceDifferentials: [
      { diagnosis: "ST-elevation myocardial infarction", rationale: "Classic radiating central chest pain + diaphoresis + ST elevation.", mustNotMiss: true },
      { diagnosis: "Aortic dissection", rationale: "Must exclude tearing pain radiating to back before anticoagulating.", mustNotMiss: true },
      { diagnosis: "Unstable angina", rationale: "Similar presentation without ST elevation — excluded here by ECG." },
    ],
    management: [
      { label: "Obtain ECG within 10 minutes", description: "Time-critical first step for any suspected ACS.", critical: true },
      { label: "Activate primary PCI / cath lab", description: "Door-to-balloon target <90 minutes for STEMI.", critical: true },
      { label: "Give aspirin 325mg chewed", description: "Antiplatelet loading dose.", critical: true },
      { label: "Give sublingual nitroglycerin without checking BP", description: "Dangerous in a hypotensive, possibly right-ventricular-involved STEMI.", unsafe: true },
      { label: "Start high-flow oxygen regardless of SpO2", description: "Routine oxygen in a non-hypoxic ACS patient offers no proven benefit and can cause harm.", unsafe: true },
      { label: "Give supplemental oxygen to target SpO2 >=94%", description: "Appropriate, titrated oxygen therapy." },
    ],
    criticalActions: ["Obtain ECG within 10 minutes", "Activate primary PCI / cath lab", "Give aspirin 325mg chewed"],
    unsafeActions: ["Give sublingual nitroglycerin without checking BP", "Start high-flow oxygen regardless of SpO2"],
    prescriptionContext: {
      ageYears: 58, weightKg: 82, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "normal", hepaticFunction: "normal",
      currentMedications: ["amlodipine", "atorvastatin"], diagnoses: ["ST-elevation myocardial infarction"],
    },
    prescriptionReference: [
      { genericName: "aspirin", formulation: "chewable tablet", strength: "325 mg", route: "oral", frequency: "once, then 75mg daily", duration: "ongoing", indication: "Antiplatelet loading for ACS" },
      { genericName: "ticagrelor", formulation: "tablet", strength: "180 mg", route: "oral", frequency: "loading dose then 90mg BD", duration: "12 months", indication: "Dual antiplatelet therapy" },
      { genericName: "atorvastatin", formulation: "tablet", strength: "80 mg", route: "oral", frequency: "once daily", duration: "ongoing", indication: "High-intensity statin post-ACS" },
    ],
    referenceDx: "ST-elevation myocardial infarction (anterior)",
    viva: [
      { stage: "case", prompt: "What is your provisional diagnosis and which single finding most strongly supports it?", points: ["STEMI", "ST elevation on ECG is the defining finding"] },
      { stage: "case", prompt: "Why is time to reperfusion the most important variable in this case?", points: ["Myocardium at risk", "door-to-balloon <90 min target"] },
      { stage: "drug", prompt: "Why avoid nitroglycerin before checking blood pressure here?", points: ["Risk of profound hypotension", "possible RV infarct dependence on preload"] },
    ],
    debrief: {
      pearls: [
        "Time is muscle — ECG and cath lab activation must not wait for troponin.",
        "Check BP before nitrates in any ACS presentation; avoid in suspected RV infarction.",
        "Routine high-flow oxygen in a non-hypoxic ACS patient is not evidence-based and can be harmful.",
      ],
      references: ["ESC Guidelines for the management of acute STEMI", "ACC/AHA STEMI Guideline"],
    },
  },

  {
    slug: "EDU-CARD-002",
    title: "Intermittent Chest Tightness Without ST Elevation",
    specialty: "Cardiology",
    difficulty: "ADVANCED",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE"],
    patientSex: "female",
    patientAgeBand: "60-64",
    patientAgeExact: 63,
    chiefComplaint: "Intermittent chest tightness over 2 days, worse at rest this morning",
    learningObjectives: ["Differentiate NSTEMI from unstable angina", "Apply risk stratification (troponin trend, ECG dynamic changes)"],
    presentation: "A 63-year-old woman with diabetes presents with intermittent chest tightness for two days, now more persistent and occurring at rest.",
    initialVitals: { hr: 92, sbp: 138, dbp: 84, rr: 18, spo2: 97, tempC: 37.0, gcs: 15, status: "stable" },
    history: [
      { q: "Describe the pain character.", category: "presenting-complaint", a: "A tightness, not sharp, comes and goes.", key: true },
      { q: "Any pain at rest today?", category: "presenting-complaint", a: "Yes, this morning it happened while I was sitting.", key: true },
      { q: "Do you have diabetes?", category: "past-medical", a: "Yes, type 2 for 10 years.", key: true },
      { q: "Any shortness of breath with exertion recently?", category: "associated-symptoms", a: "Yes, more than usual this week." },
      { q: "Any prior heart problems?", category: "past-medical", a: "No, first time." },
      { q: "Do you smoke or drink alcohol?", category: "social", a: "Never smoked, occasional alcohol." },
    ],
    exam: [
      { system: "cardiovascular", finding: "Regular rate, no murmur, no gallop." },
      { system: "respiratory", finding: "Clear bilaterally." },
      { system: "general", finding: "Mildly anxious, comfortable at rest now.", key: true },
    ],
    investigations: [
      { name: "12-lead ECG", category: "ecg", indication: "Suspected ACS", turnaround: 2, result: "T-wave inversion in V4-V6, no ST elevation.", interpretation: "Dynamic ischemic changes, consistent with NSTEMI/UA.", diagnostic: true },
      { name: "Troponin I (serial)", category: "biochemistry", indication: "Risk stratify ACS", turnaround: 45, result: "First: 0.09 ng/mL; repeat at 3h: 0.35 ng/mL (rising).", interpretation: "Rising troponin confirms NSTEMI.", diagnostic: true },
      { name: "HbA1c", category: "biochemistry", indication: "Diabetes control assessment", turnaround: 60, result: "8.2%.", interpretation: "Poor glycemic control, relevant to overall risk but not acutely diagnostic." },
      { name: "Chest X-ray", category: "xray", indication: "Baseline", turnaround: 20, result: "Unremarkable.", interpretation: "No acute pulmonary process." },
    ],
    redFlags: ["Rest pain in a diabetic patient", "Rising troponin", "Dynamic ECG changes"],
    referenceDifferentials: [
      { diagnosis: "NSTEMI", rationale: "Rising troponin with dynamic ECG changes and rest pain.", mustNotMiss: true },
      { diagnosis: "Unstable angina", rationale: "Would present similarly but without troponin rise." },
      { diagnosis: "Gastroesophageal reflux", rationale: "Common mimic, but doesn't explain rising troponin.", },
    ],
    management: [
      { label: "Start dual antiplatelet therapy", description: "Aspirin + P2Y12 inhibitor per NSTE-ACS pathway.", critical: true },
      { label: "Risk-stratify with GRACE score", description: "Determines timing of invasive strategy.", critical: true },
      { label: "Arrange early invasive angiography", description: "Within 24-72h per risk category.", critical: true },
      { label: "Discharge home with outpatient follow-up", description: "Inappropriate given rising troponin and ongoing rest symptoms.", unsafe: true },
    ],
    criticalActions: ["Start dual antiplatelet therapy", "Risk-stratify with GRACE score", "Arrange early invasive angiography"],
    unsafeActions: ["Discharge home with outpatient follow-up"],
    prescriptionContext: {
      ageYears: 63, weightKg: 70, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "normal", hepaticFunction: "normal",
      currentMedications: ["metformin"], diagnoses: ["NSTEMI", "type 2 diabetes"],
    },
    prescriptionReference: [
      { genericName: "aspirin", formulation: "tablet", strength: "75 mg", route: "oral", frequency: "once daily", duration: "ongoing", indication: "Secondary prevention" },
      { genericName: "clopidogrel", formulation: "tablet", strength: "75 mg", route: "oral", frequency: "once daily", duration: "12 months", indication: "Dual antiplatelet therapy" },
      { genericName: "fondaparinux", formulation: "subcutaneous injection", strength: "2.5 mg", route: "subcutaneous", frequency: "once daily", duration: "until angiography", indication: "Anticoagulation in NSTE-ACS" },
    ],
    referenceDx: "Non-ST-elevation myocardial infarction (NSTEMI)",
    viva: [
      { stage: "case", prompt: "How does NSTEMI differ from unstable angina at the biochemical level?", points: ["Troponin elevation reflects myocardial necrosis in NSTEMI"] },
      { stage: "case", prompt: "What determines whether this patient needs urgent vs. early invasive angiography?", points: ["GRACE score", "ongoing symptoms/hemodynamic instability"] },
    ],
    debrief: {
      pearls: ["A normal single troponin does not exclude NSTEMI — always trend it.", "Diabetics can have atypical or reduced anginal pain."],
      references: ["ESC NSTE-ACS Guidelines"],
    },
  },

  {
    slug: "EDU-CARD-003",
    title: "Progressive Breathlessness and Leg Swelling",
    specialty: "Cardiology",
    subspecialty: "Heart Failure",
    difficulty: "INTERMEDIATE",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE", "NURSING", "PHYSIOTHERAPY"],
    patientSex: "male",
    patientAgeBand: "70-74",
    chiefComplaint: "Worsening breathlessness and leg swelling over 2 weeks",
    learningObjectives: ["Diagnose decompensated heart failure", "Differentiate cardiac vs. pulmonary causes of dyspnea", "Plan diuretic and fluid management"],
    presentation: "A 72-year-old man with known ischemic heart disease presents with two weeks of worsening breathlessness, orthopnea, and bilateral leg swelling.",
    initialVitals: { hr: 96, sbp: 148, dbp: 88, rr: 24, spo2: 91, tempC: 36.8, gcs: 15, status: "concern" },
    history: [
      { q: "How many pillows do you sleep with?", category: "presenting-complaint", a: "Three now, used to be one.", key: true },
      { q: "Any waking up gasping for breath at night?", category: "associated-symptoms", a: "Yes, twice this week.", key: true },
      { q: "Any chest pain?", category: "presenting-complaint", a: "No chest pain." },
      { q: "Do you have a history of heart attacks?", category: "past-medical", a: "Yes, one 5 years ago." },
      { q: "Any weight gain recently?", category: "presenting-complaint", a: "About 4 kg in 2 weeks.", key: true },
      { q: "Are you taking your heart medications regularly?", category: "medications", a: "I ran out of my furosemide a week ago." , key: true},
    ],
    exam: [
      { system: "cardiovascular", finding: "Raised JVP to angle of jaw, displaced apex beat, S3 gallop.", key: true },
      { system: "respiratory", finding: "Bilateral basal crackles.", key: true },
      { system: "general", finding: "Bilateral pitting pedal edema to mid-shin.", key: true },
      { system: "abdominal", finding: "Mild hepatomegaly, tender." },
    ],
    investigations: [
      { name: "BNP / NT-proBNP", category: "biochemistry", indication: "Suspected heart failure", turnaround: 60, result: "NT-proBNP 4200 pg/mL (markedly elevated).", interpretation: "Strongly supports acute decompensated heart failure.", diagnostic: true },
      { name: "Chest X-ray", category: "xray", indication: "Assess pulmonary congestion", turnaround: 20, result: "Cardiomegaly, bilateral interstitial infiltrates, Kerley B lines.", interpretation: "Pulmonary edema.", diagnostic: true },
      { name: "Echocardiogram", category: "echo", indication: "Assess LV function", turnaround: 90, result: "LVEF 30%, global hypokinesia.", interpretation: "Heart failure with reduced ejection fraction.", diagnostic: true },
      { name: "Renal function panel", category: "biochemistry", indication: "Baseline before diuresis", turnaround: 45, result: "Creatinine 1.3 mg/dL, potassium 4.1 mmol/L.", interpretation: "Mildly impaired, monitor during diuresis." },
    ],
    redFlags: ["Hypoxia with pulmonary edema", "Medication non-adherence", "Rapid weight gain"],
    referenceDifferentials: [
      { diagnosis: "Acute decompensated heart failure", rationale: "Orthopnea, PND, raised JVP, S3, pulmonary edema on CXR.", mustNotMiss: true },
      { diagnosis: "COPD exacerbation", rationale: "Can mimic dyspnea but lacks JVP/S3/edema pattern." },
      { diagnosis: "Pulmonary embolism", rationale: "Consider if sudden onset or risk factors present; less supported here.", mustNotMiss: true },
    ],
    management: [
      { label: "IV loop diuretic (furosemide)", description: "First-line for volume overload in decompensated HF.", critical: true },
      { label: "Sit patient upright, supplemental oxygen to target SpO2", description: "Symptomatic relief and correct hypoxia.", critical: true },
      { label: "Daily weight and strict fluid balance monitoring", description: "Titrate diuresis safely." },
      { label: "Restart and reconcile guideline-directed heart failure therapy", description: "ACE-inhibitor/ARNI, beta-blocker, MRA, SGLT2 inhibitor as tolerated.", critical: true },
      { label: "Aggressive IV fluid bolus for 'better perfusion'", description: "Worsens volume overload in decompensated HF.", unsafe: true },
    ],
    criticalActions: ["IV loop diuretic (furosemide)", "Sit patient upright, supplemental oxygen to target SpO2", "Restart and reconcile guideline-directed heart failure therapy"],
    unsafeActions: ["Aggressive IV fluid bolus for 'better perfusion'"],
    prescriptionContext: {
      ageYears: 72, weightKg: 78, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "impaired", hepaticFunction: "normal",
      currentMedications: ["aspirin", "atorvastatin"], diagnoses: ["heart failure with reduced ejection fraction"],
    },
    prescriptionReference: [
      { genericName: "furosemide", formulation: "IV injection", strength: "40 mg", route: "intravenous", frequency: "BD, titrate to response", duration: "until euvolemic, then oral", indication: "Decongestion", monitoring: "Daily weight, renal function, potassium" },
      { genericName: "sacubitril/valsartan", formulation: "tablet", strength: "24/26 mg", route: "oral", frequency: "twice daily", duration: "ongoing", indication: "Guideline-directed HFrEF therapy" },
      { genericName: "spironolactone", formulation: "tablet", strength: "25 mg", route: "oral", frequency: "once daily", duration: "ongoing", indication: "Mineralocorticoid receptor antagonist", monitoring: "Potassium and renal function" },
    ],
    referenceDx: "Acute decompensated heart failure with reduced ejection fraction",
    viva: [
      { stage: "case", prompt: "What examination findings distinguish cardiac from pulmonary causes of this dyspnea?", points: ["Raised JVP", "S3 gallop", "peripheral edema"] },
      { stage: "case", prompt: "Why was medication non-adherence a critical part of this history?", points: ["Missed furosemide precipitated decompensation"] },
    ],
    debrief: {
      pearls: ["Medication non-adherence is one of the most common precipitants of decompensated HF.", "Daily weights are a simple, high-value monitoring tool during diuresis."],
      references: ["ESC Heart Failure Guidelines", "ACC/AHA/HFSA Heart Failure Guideline"],
    },
  },

  {
    slug: "EDU-RESP-001",
    title: "Fever, Cough and Pleuritic Chest Pain",
    specialty: "Pulmonology",
    difficulty: "FOUNDATION",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE", "NURSING", "DIAGNOSTICS"],
    patientSex: "female",
    patientAgeBand: "30-34",
    chiefComplaint: "Fever, productive cough and right-sided chest pain for 3 days",
    learningObjectives: ["Diagnose community-acquired pneumonia", "Apply CURB-65 for site-of-care decisions", "Select appropriate empirical antibiotics"],
    presentation: "A 32-year-old woman presents with 3 days of fever, productive cough with rust-colored sputum, and right-sided pleuritic chest pain.",
    initialVitals: { hr: 104, sbp: 112, dbp: 70, rr: 24, spo2: 93, tempC: 39.1, gcs: 15, status: "concern" },
    history: [
      { q: "What color is the sputum?", category: "presenting-complaint", a: "Rusty/brownish.", key: true },
      { q: "Does the chest pain change with breathing?", category: "presenting-complaint", a: "Yes, it's worse when I breathe in deeply.", key: true },
      { q: "Any confusion or feeling unusually drowsy?", category: "associated-symptoms", a: "No, I feel alert." },
      { q: "Any chronic lung disease?", category: "past-medical", a: "No." },
      { q: "Do you smoke?", category: "social", a: "No." },
    ],
    exam: [
      { system: "respiratory", finding: "Decreased breath sounds and dullness to percussion at right base, bronchial breathing, crackles.", key: true },
      { system: "general", finding: "Febrile, mild respiratory distress.", key: true },
      { system: "cardiovascular", finding: "Tachycardic, otherwise normal." },
    ],
    investigations: [
      { name: "Chest X-ray", category: "xray", indication: "Suspected pneumonia", turnaround: 20, result: "Right lower lobe consolidation.", interpretation: "Confirms lobar pneumonia.", diagnostic: true },
      { name: "CBC", category: "hematology", indication: "Assess infection severity", turnaround: 30, result: "WBC 16,200/uL, neutrophil predominant.", interpretation: "Bacterial infection pattern.", diagnostic: true },
      { name: "Blood cultures", category: "microbiology", indication: "Before antibiotics if severe", turnaround: 2880, result: "Pending at time of initial management.", interpretation: "Send before first antibiotic dose if possible without delaying treatment." },
      { name: "Sputum culture", category: "microbiology", indication: "Guide antibiotic therapy", turnaround: 1440, result: "Pending.", interpretation: "Useful but should not delay empirical therapy." },
    ],
    redFlags: ["RR >=22", "SpO2 <94% on room air", "CURB-65 >=2"],
    referenceDifferentials: [
      { diagnosis: "Community-acquired pneumonia", rationale: "Fever, productive cough, pleuritic pain, focal consolidation on CXR.", mustNotMiss: true },
      { diagnosis: "Pulmonary embolism", rationale: "Can present with pleuritic pain; less likely given fever and consolidation.", mustNotMiss: true },
      { diagnosis: "Pleurisy (viral)", rationale: "Would not typically show lobar consolidation." },
    ],
    management: [
      { label: "Calculate CURB-65 score", description: "Guides site-of-care (outpatient vs admission).", critical: true },
      { label: "Start empirical antibiotics within 4 hours", description: "Timely antibiotics improve outcomes in CAP.", critical: true },
      { label: "Supplemental oxygen to target SpO2 >=94%", description: "Correct hypoxia.", critical: true },
      { label: "Discharge without antibiotics pending sputum culture", description: "Unsafe delay in a hypoxic, tachypneic patient.", unsafe: true },
    ],
    criticalActions: ["Calculate CURB-65 score", "Start empirical antibiotics within 4 hours", "Supplemental oxygen to target SpO2 >=94%"],
    unsafeActions: ["Discharge without antibiotics pending sputum culture"],
    prescriptionContext: {
      ageYears: 32, weightKg: 60, allergies: [], pregnancyStatus: "not-pregnant",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["community-acquired pneumonia"],
    },
    prescriptionReference: [
      { genericName: "amoxicillin-clavulanate", formulation: "IV injection", strength: "1.2 g", route: "intravenous", frequency: "TDS", duration: "5-7 days, step down to oral when stable", indication: "Empirical CAP coverage" },
      { genericName: "azithromycin", formulation: "tablet", strength: "500 mg", route: "oral", frequency: "once daily", duration: "3 days", indication: "Atypical organism coverage" },
      { genericName: "paracetamol", formulation: "tablet", strength: "650 mg", route: "oral", frequency: "QID PRN", duration: "as needed for fever", indication: "Antipyretic/analgesic" },
    ],
    referenceDx: "Community-acquired pneumonia (right lower lobe)",
    viva: [
      { stage: "case", prompt: "What does the CURB-65 score guide, and what is this patient's score?", points: ["Site of care decision", "score components: confusion, urea, RR, BP, age"] },
      { stage: "drug", prompt: "Why cover atypical organisms empirically in CAP?", points: ["Mycoplasma/Chlamydophila/Legionella are common and not covered by beta-lactams alone"] },
    ],
    debrief: {
      pearls: ["Don't wait for sputum/blood culture results to start antibiotics in CAP.", "Rust-colored sputum classically suggests pneumococcal pneumonia."],
      references: ["IDSA/ATS CAP Guidelines"],
    },
  },

  {
    slug: "EDU-RESP-002",
    title: "Sudden Wheeze and Breathlessness After Exercise",
    specialty: "Pulmonology",
    difficulty: "FOUNDATION",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "female",
    patientAgeBand: "15-19",
    chiefComplaint: "Sudden wheeze and breathlessness after running",
    learningObjectives: ["Assess acute asthma severity", "Apply stepwise bronchodilator/steroid therapy", "Recognize life-threatening asthma features"],
    presentation: "A 17-year-old girl with known asthma presents with acute wheeze and breathlessness that started while running, not relieved by her rescue inhaler.",
    initialVitals: { hr: 118, sbp: 118, dbp: 76, rr: 28, spo2: 92, tempC: 37.0, gcs: 15, status: "concern" },
    history: [
      { q: "How many puffs of your inhaler have you used?", category: "presenting-complaint", a: "Six puffs in the last hour, no relief.", key: true },
      { q: "Can you speak in full sentences?", category: "presenting-complaint", a: "No, only a few words at a time.", key: true },
      { q: "Any previous ICU admissions for asthma?", category: "past-medical", a: "Yes, once two years ago.", key: true },
      { q: "Do you use a preventer inhaler regularly?", category: "medications", a: "Not really, only when I remember." },
      { q: "Any known triggers?", category: "presenting-complaint", a: "Exercise and pollen season." },
    ],
    exam: [
      { system: "respiratory", finding: "Widespread expiratory wheeze, prolonged expiration, using accessory muscles.", key: true },
      { system: "general", finding: "Speaking in words, not sentences, visibly distressed.", key: true },
      { system: "cardiovascular", finding: "Tachycardic, pulsus paradoxus noted.", key: true },
    ],
    investigations: [
      { name: "Peak expiratory flow rate", category: "special", indication: "Assess asthma severity", turnaround: 2, result: "38% of predicted/best.", interpretation: "Severe exacerbation.", diagnostic: true },
      { name: "SpO2 / ABG", category: "abg-vbg", indication: "Assess for respiratory failure", turnaround: 10, result: "pH 7.38, pCO2 38 mmHg, pO2 68 mmHg.", interpretation: "Near-normal CO2 in severe asthma is a warning sign of fatigue, not reassurance.", diagnostic: true },
      { name: "Chest X-ray", category: "xray", indication: "Exclude pneumothorax/consolidation", turnaround: 20, result: "Hyperinflated lungs, no pneumothorax.", interpretation: "Consistent with acute asthma, no complication." },
    ],
    redFlags: ["Inability to speak full sentences", "Silent chest (if progresses)", "Normal/rising CO2 in a tachypneic patient"],
    referenceDifferentials: [
      { diagnosis: "Acute severe asthma exacerbation", rationale: "Known asthmatic, wheeze, low PEFR, poor inhaler response.", mustNotMiss: true },
      { diagnosis: "Anaphylaxis", rationale: "Consider if triggers/urticaria present; not supported here." },
      { diagnosis: "Pneumothorax", rationale: "Excluded by chest X-ray." },
    ],
    management: [
      { label: "Nebulized salbutamol + ipratropium, back to back", description: "First-line bronchodilation for severe exacerbation.", critical: true },
      { label: "Systemic corticosteroids (oral or IV)", description: "Reduces airway inflammation, prevents relapse.", critical: true },
      { label: "Continuous SpO2 monitoring, oxygen to target 94-98%", description: "Correct hypoxia safely.", critical: true },
      { label: "Sedate for anxiety", description: "Sedation can precipitate respiratory arrest in severe asthma.", unsafe: true },
    ],
    criticalActions: ["Nebulized salbutamol + ipratropium, back to back", "Systemic corticosteroids (oral or IV)", "Continuous SpO2 monitoring, oxygen to target 94-98%"],
    unsafeActions: ["Sedate for anxiety"],
    prescriptionContext: {
      ageYears: 17, weightKg: 55, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: ["salbutamol inhaler PRN"], diagnoses: ["acute severe asthma exacerbation"],
    },
    prescriptionReference: [
      { genericName: "salbutamol", formulation: "nebulizer solution", strength: "5 mg", route: "inhalation", frequency: "back-to-back x3, then as needed", duration: "acute phase", indication: "Bronchodilation" },
      { genericName: "prednisolone", formulation: "tablet", strength: "40 mg", route: "oral", frequency: "once daily", duration: "5 days", indication: "Systemic anti-inflammatory" },
      { genericName: "ipratropium bromide", formulation: "nebulizer solution", strength: "500 mcg", route: "inhalation", frequency: "with first 3 salbutamol doses", duration: "acute phase", indication: "Additional bronchodilation in severe exacerbation" },
    ],
    referenceDx: "Acute severe asthma exacerbation",
    viva: [
      { stage: "case", prompt: "Why is a 'normal' CO2 concerning in this severe asthma patient?", points: ["Suggests fatigue and impending respiratory failure, not reassurance"] },
      { stage: "emergency", prompt: "What clinical feature would make you call this life-threatening asthma?", points: ["Silent chest, cyanosis, exhaustion, altered consciousness, bradycardia"] },
    ],
    debrief: {
      pearls: ["Poor inhaler technique/adherence is a common precipitant — always ask.", "A 'normalizing' CO2 in severe asthma signals fatigue, not improvement."],
      references: ["GINA Global Strategy for Asthma Management"],
    },
  },

  {
    slug: "EDU-RESP-003",
    title: "Worsening Breathlessness in a Long-Term Smoker",
    specialty: "Pulmonology",
    difficulty: "INTERMEDIATE",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE", "NURSING", "PHYSIOTHERAPY"],
    patientSex: "male",
    patientAgeBand: "65-69",
    chiefComplaint: "Worsening breathlessness and increased sputum over 4 days",
    learningObjectives: ["Diagnose an infective COPD exacerbation", "Use controlled oxygen therapy safely in COPD", "Recognize CO2 retention risk"],
    presentation: "A 67-year-old man with known COPD presents with 4 days of worsening breathlessness, increased sputum volume, and change in sputum color to yellow-green.",
    initialVitals: { hr: 102, sbp: 132, dbp: 82, rr: 26, spo2: 86, tempC: 37.6, gcs: 15, status: "concern" },
    history: [
      { q: "Has your sputum changed in color or amount?", category: "presenting-complaint", a: "Yes, more of it and yellow-green now.", key: true },
      { q: "How many pack-years have you smoked?", category: "social", a: "About 45 pack-years, quit 2 years ago.", key: true },
      { q: "Do you use home oxygen?", category: "past-medical", a: "Yes, 2L/min at night." },
      { q: "Any fever?", category: "associated-symptoms", a: "Mild fever yesterday." },
      { q: "Any previous hospital admissions for COPD?", category: "past-medical", a: "Three in the last year.", key: true },
    ],
    exam: [
      { system: "respiratory", finding: "Bilateral wheeze, prolonged expiration, using accessory muscles, pursed-lip breathing.", key: true },
      { system: "general", finding: "Barrel chest, cyanosis of lips.", key: true },
      { system: "cardiovascular", finding: "No signs of cor pulmonale currently." },
    ],
    investigations: [
      { name: "Arterial blood gas", category: "abg-vbg", indication: "Assess for CO2 retention/respiratory failure", turnaround: 10, result: "pH 7.31, pCO2 62 mmHg, pO2 52 mmHg, HCO3 28.", interpretation: "Acute-on-chronic respiratory acidosis — type 2 respiratory failure.", diagnostic: true },
      { name: "Chest X-ray", category: "xray", indication: "Exclude pneumonia/pneumothorax", turnaround: 20, result: "Hyperinflated lung fields, no consolidation.", interpretation: "Consistent with COPD, no pneumonia." },
      { name: "Sputum culture", category: "microbiology", indication: "Guide antibiotic choice", turnaround: 1440, result: "Pending.", interpretation: "Send but don't delay empirical treatment." },
      { name: "CBC", category: "hematology", indication: "Assess infection/polycythemia", turnaround: 30, result: "WBC 13,800/uL, Hb 17.8 g/dL (secondary polycythemia).", interpretation: "Supports infective exacerbation with chronic hypoxia." },
    ],
    redFlags: ["SpO2 <88% at baseline", "Rising CO2 with acidosis", "Frequent prior admissions"],
    referenceDifferentials: [
      { diagnosis: "Infective exacerbation of COPD", rationale: "Increased sputum purulence/volume, known COPD, hypoxia, hypercapnia.", mustNotMiss: true },
      { diagnosis: "Pneumonia", rationale: "Excluded by chest X-ray (no consolidation)." },
      { diagnosis: "Pulmonary embolism", rationale: "Always consider in acute decompensation; risk factors should be assessed.", mustNotMiss: true },
    ],
    management: [
      { label: "Controlled oxygen therapy titrated to SpO2 88-92%", description: "Avoids CO2 narcosis risk in chronic retainers.", critical: true },
      { label: "Nebulized bronchodilators (salbutamol + ipratropium)", description: "First-line bronchodilation." , critical: true},
      { label: "Systemic corticosteroids", description: "Reduces airway inflammation, shortens recovery." , critical: true},
      { label: "Empirical antibiotics given purulent sputum", description: "Indicated per Anthonisen criteria." },
      { label: "High-flow oxygen to achieve SpO2 100%", description: "Risk of worsening hypercapnic respiratory failure/CO2 narcosis in a chronic retainer.", unsafe: true },
    ],
    criticalActions: ["Controlled oxygen therapy titrated to SpO2 88-92%", "Nebulized bronchodilators (salbutamol + ipratropium)", "Systemic corticosteroids"],
    unsafeActions: ["High-flow oxygen to achieve SpO2 100%"],
    prescriptionContext: {
      ageYears: 67, weightKg: 68, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: ["tiotropium inhaler", "home oxygen"], diagnoses: ["COPD exacerbation"],
    },
    prescriptionReference: [
      { genericName: "prednisolone", formulation: "tablet", strength: "30 mg", route: "oral", frequency: "once daily", duration: "5 days", indication: "Systemic anti-inflammatory" },
      { genericName: "amoxicillin-clavulanate", formulation: "tablet", strength: "625 mg", route: "oral", frequency: "TDS", duration: "5 days", indication: "Empirical coverage for purulent exacerbation" },
      { genericName: "salbutamol", formulation: "nebulizer solution", strength: "2.5 mg", route: "inhalation", frequency: "QID PRN", duration: "acute phase", indication: "Bronchodilation" },
    ],
    referenceDx: "Acute infective exacerbation of COPD with type 2 respiratory failure",
    viva: [
      { stage: "case", prompt: "Why target SpO2 88-92% instead of maximal oxygen in this patient?", points: ["Risk of hypercapnic respiratory failure/CO2 narcosis in chronic CO2 retainers"] },
      { stage: "case", prompt: "What ABG finding indicates this is acute-on-chronic, not purely acute?", points: ["Elevated bicarbonate reflects chronic renal compensation for chronic hypercapnia"] },
    ],
    debrief: {
      pearls: ["Controlled oxygen therapy is a critical, frequently-missed safety step in COPD.", "Elevated bicarbonate on ABG signals chronic compensation, not an acute process alone."],
      references: ["GOLD Global Strategy for COPD"],
    },
  },
];
