import type { CaseDef } from "../builder";

export const endocrineRenalInfectiousCases: CaseDef[] = [
  {
    slug: "EDU-ENDO-001",
    title: "Vomiting, Abdominal Pain and Deep Breathing in a Diabetic Teenager",
    specialty: "Endocrinology",
    difficulty: "ADVANCED",
    acuity: "EMERGENCY",
    learnerTracks: ["MEDICINE", "NURSING", "PHARMACY"],
    patientSex: "female",
    patientAgeBand: "15-19",
    patientAgeExact: 16,
    chiefComplaint: "Vomiting, abdominal pain, and unusual deep breathing for 1 day",
    learningObjectives: ["Diagnose diabetic ketoacidosis", "Sequence fluid, insulin and potassium management safely", "Avoid cerebral edema in pediatric DKA"],
    presentation: "A 16-year-old girl with type 1 diabetes presents with a day of vomiting, abdominal pain, and deep, rapid breathing. Her mother says she's been drinking huge amounts of water.",
    initialVitals: { hr: 128, sbp: 98, dbp: 60, rr: 32, spo2: 98, tempC: 37.1, gcs: 14, status: "critical" },
    history: [
      { q: "Have you been passing more urine than usual?", category: "presenting-complaint", a: "Yes, constantly, and drinking a lot of water too.", key: true },
      { q: "Have you missed any insulin doses?", category: "medications", a: "I ran out of insulin 2 days ago.", key: true },
      { q: "Any fever or recent infection?", category: "associated-symptoms", a: "No fever, felt fine until yesterday." },
      { q: "How long have you had diabetes?", category: "past-medical", a: "Type 1, diagnosed 3 years ago." },
      { q: "Any confusion or drowsiness?", category: "associated-symptoms", a: "Yes, I feel a bit foggy.", key: true },
    ],
    exam: [
      { system: "respiratory", finding: "Deep, sighing (Kussmaul) breathing.", key: true },
      { system: "general", finding: "Dry mucous membranes, reduced skin turgor, fruity breath odor.", key: true },
      { system: "abdominal", finding: "Diffuse mild tenderness, no rebound/guarding.", key: true },
      { system: "mental-status", finding: "Drowsy but rousable, GCS 14.", key: true },
    ],
    investigations: [
      { name: "Capillary/blood glucose", category: "biochemistry", indication: "Suspected DKA", turnaround: 2, result: "486 mg/dL.", interpretation: "Severe hyperglycemia.", diagnostic: true },
      { name: "Venous blood gas", category: "abg-vbg", indication: "Assess acidosis severity", turnaround: 10, result: "pH 7.05, HCO3 8 mmol/L.", interpretation: "Severe metabolic acidosis consistent with DKA.", diagnostic: true },
      { name: "Serum/urine ketones", category: "biochemistry", indication: "Confirm ketosis", turnaround: 15, result: "Serum ketones 5.8 mmol/L, urine ketones 3+.", interpretation: "Confirms ketoacidosis.", diagnostic: true },
      { name: "Serum electrolytes", category: "biochemistry", indication: "Guide potassium replacement", turnaround: 30, result: "K+ 5.2 mmol/L, Na+ 129 mmol/L (corrected ~134).", interpretation: "Potassium currently normal/high due to acidosis but WILL fall rapidly with insulin — replace proactively.", diagnostic: true },
    ],
    redFlags: ["GCS drop", "pH <7.1", "Risk of cerebral edema with over-rapid fluid correction"],
    referenceDifferentials: [
      { diagnosis: "Diabetic ketoacidosis", rationale: "Hyperglycemia + ketosis + metabolic acidosis + Kussmaul breathing.", mustNotMiss: true },
      { diagnosis: "Acute gastroenteritis", rationale: "Vomiting/abdominal pain overlap, but doesn't explain glucose/ketones/acidosis." },
      { diagnosis: "Sepsis with metabolic acidosis", rationale: "Consider as a co-precipitant; no fever/focal source here but should stay on the list.", mustNotMiss: true },
    ],
    management: [
      { label: "IV isotonic fluid bolus (careful, weight-based in pediatrics)", description: "Correct dehydration slowly to reduce cerebral edema risk.", critical: true },
      { label: "Start IV insulin infusion (0.1 U/kg/hr) — only after initial fluids started", description: "Insulin before adequate fluid resuscitation risks rapid osmotic shifts.", critical: true },
      { label: "Add potassium to IV fluids once K+ confirmed <5.5 and urine output present", description: "Insulin drives K+ into cells; anticipatory replacement prevents fatal hypokalemia.", critical: true },
      { label: "Give an initial IV insulin bolus", description: "Insulin boluses in pediatric DKA increase risk of cerebral edema and are avoided.", unsafe: true },
      { label: "Rapidly correct glucose to normal within 2 hours with aggressive fluids/insulin", description: "Overly rapid correction is a major risk factor for cerebral edema in pediatric DKA.", unsafe: true },
      { label: "Monitor neuro status hourly for cerebral edema signs", description: "Headache, altered consciousness, bradycardia, hypertension warrant immediate action." },
    ],
    criticalActions: ["IV isotonic fluid bolus (careful, weight-based in pediatrics)", "Start IV insulin infusion (0.1 U/kg/hr) — only after initial fluids started", "Add potassium to IV fluids once K+ confirmed <5.5 and urine output present"],
    unsafeActions: ["Give an initial IV insulin bolus", "Rapidly correct glucose to normal within 2 hours with aggressive fluids/insulin"],
    prescriptionContext: {
      ageYears: 16, weightKg: 54, allergies: [], pregnancyStatus: "not-pregnant",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: ["insulin (lapsed)"], diagnoses: ["diabetic ketoacidosis"],
    },
    prescriptionReference: [
      { genericName: "regular insulin", formulation: "IV infusion", strength: "0.1 U/kg/hr", route: "intravenous", frequency: "continuous infusion", duration: "until anion gap closes", indication: "Ketoacidosis correction", monitoring: "Hourly glucose, 2-4 hourly electrolytes" },
      { genericName: "potassium chloride", formulation: "IV additive", strength: "20-40 mmol/L of fluid", route: "intravenous", frequency: "with maintenance fluids", duration: "until K+ stable", indication: "Prevent insulin-induced hypokalemia", monitoring: "Serum potassium, cardiac monitor" },
      { genericName: "sodium chloride 0.9%", formulation: "IV infusion", strength: "isotonic", route: "intravenous", frequency: "per weight-based protocol", duration: "first 24-48h", indication: "Rehydration" },
    ],
    referenceDx: "Diabetic ketoacidosis (severe)",
    viva: [
      { stage: "emergency", prompt: "Why is an insulin bolus considered unsafe in pediatric DKA?", points: ["Increases cerebral edema risk from rapid osmotic shifts"] },
      { stage: "case", prompt: "Why add potassium to fluids even when the initial level is normal or high?", points: ["Insulin drives potassium intracellularly; total body potassium is usually depleted despite normal serum level"] },
    ],
    debrief: {
      pearls: ["Fluids before insulin, always, especially in children.", "Total body potassium is depleted in DKA even when serum K+ looks normal or high at presentation."],
      references: ["ISPAD Clinical Practice Consensus Guidelines: DKA", "ADA DKA Management Guidelines"],
    },
  },

  {
    slug: "EDU-ENDO-002",
    title: "Sweating, Confusion and Tremor in a Known Diabetic",
    specialty: "Endocrinology",
    difficulty: "FOUNDATION",
    acuity: "EMERGENCY",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "male",
    patientAgeBand: "60-64",
    chiefComplaint: "Sudden sweating, shakiness and confusion",
    learningObjectives: ["Recognize and immediately treat severe hypoglycemia", "Understand sulfonylurea-induced prolonged hypoglycemia risk"],
    presentation: "A 62-year-old man on oral hypoglycemic agents is found by his family confused, sweaty, and trembling before a meal.",
    initialVitals: { hr: 112, sbp: 128, dbp: 80, rr: 18, spo2: 98, tempC: 36.5, gcs: 13, status: "concern" },
    history: [
      { q: "What diabetes medications does he take?", category: "medications", a: "Glimepiride and metformin.", key: true },
      { q: "Did he eat his last meal?", category: "presenting-complaint", a: "Family says he skipped lunch today.", key: true },
      { q: "Any alcohol use?", category: "social", a: "None." },
      { q: "Any history of similar episodes?", category: "past-medical", a: "Once before, milder, a few months ago." },
    ],
    exam: [
      { system: "general", finding: "Diaphoretic, tremulous, pale.", key: true },
      { system: "mental-status", finding: "Confused, disoriented to time, GCS 13.", key: true },
      { system: "cardiovascular", finding: "Tachycardic, otherwise normal." },
    ],
    investigations: [
      { name: "Capillary blood glucose", category: "biochemistry", indication: "Suspected hypoglycemia", turnaround: 1, result: "38 mg/dL.", interpretation: "Severe hypoglycemia — treat immediately, do not wait for further tests.", diagnostic: true },
      { name: "Renal function panel", category: "biochemistry", indication: "Sulfonylureas accumulate in renal impairment", turnaround: 30, result: "Creatinine 1.6 mg/dL (mildly elevated).", interpretation: "Explains prolonged sulfonylurea action and risk of recurrent hypoglycemia." },
    ],
    redFlags: ["Altered mental status with glucose <54 mg/dL", "Sulfonylurea use (risk of prolonged/recurrent hypoglycemia)"],
    referenceDifferentials: [
      { diagnosis: "Sulfonylurea-induced hypoglycemia", rationale: "On glimepiride, skipped meal, confirmed low glucose.", mustNotMiss: true },
      { diagnosis: "Stroke", rationale: "Confusion could mimic stroke; always check glucose first before assuming stroke.", mustNotMiss: true },
      { diagnosis: "Sepsis", rationale: "Can cause confusion/hypoglycemia; no fever or infective source here." },
    ],
    management: [
      { label: "Check glucose immediately and treat before further workup", description: "'Glucose first' — treat hypoglycemia before extensive investigation of confusion.", critical: true },
      { label: "Give IV dextrose (or oral glucose if able to swallow safely)", description: "Rapid correction of severe hypoglycemia.", critical: true },
      { label: "Admit for observation given sulfonylurea use", description: "Sulfonylureas cause prolonged, recurrent hypoglycemia — a single correction is not enough.", critical: true },
      { label: "Discharge immediately once glucose normalizes", description: "Unsafe — sulfonylurea-induced hypoglycemia commonly recurs after initial correction.", unsafe: true },
    ],
    criticalActions: ["Check glucose immediately and treat before further workup", "Give IV dextrose (or oral glucose if able to swallow safely)", "Admit for observation given sulfonylurea use"],
    unsafeActions: ["Discharge immediately once glucose normalizes"],
    prescriptionContext: {
      ageYears: 62, weightKg: 75, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "impaired", hepaticFunction: "normal", currentMedications: ["glimepiride", "metformin"], diagnoses: ["sulfonylurea-induced hypoglycemia"],
    },
    prescriptionReference: [
      { genericName: "dextrose 25%", formulation: "IV injection", strength: "50 mL", route: "intravenous", frequency: "once, repeat as needed", duration: "acute correction", indication: "Severe hypoglycemia" },
      { genericName: "dextrose 10%", formulation: "IV infusion", strength: "maintenance rate", route: "intravenous", frequency: "continuous", duration: "24h observation", indication: "Prevent rebound hypoglycemia from sulfonylurea" },
    ],
    referenceDx: "Severe hypoglycemia secondary to sulfonylurea use",
    viva: [
      { stage: "case", prompt: "Why must this patient be admitted rather than discharged once glucose normalizes?", points: ["Sulfonylureas have long half-lives and cause recurrent hypoglycemia"] },
      { stage: "rapid-fire", prompt: "What's the first test in any acutely confused patient?", points: ["Point-of-care glucose"] },
    ],
    debrief: {
      pearls: ["'Glucose first' in any acute confusion — it's fast, cheap, and treatable.", "Sulfonylurea hypoglycemia requires observation, not a single correction."],
      references: ["Endocrine Society Hypoglycemia Guidelines"],
    },
  },

  {
    slug: "EDU-RENAL-001",
    title: "Decreasing Urine Output After a Diarrheal Illness",
    specialty: "Nephrology",
    difficulty: "INTERMEDIATE",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "male",
    patientAgeBand: "70-74",
    chiefComplaint: "Reduced urine output and generalized weakness for 2 days",
    learningObjectives: ["Classify AKI by KDIGO staging", "Differentiate pre-renal, intrinsic, and post-renal AKI", "Avoid nephrotoxic drugs in AKI"],
    presentation: "A 71-year-old man on antihypertensives presents with 2 days of markedly reduced urine output and weakness, following a week of diarrhea.",
    initialVitals: { hr: 100, sbp: 100, dbp: 62, rr: 18, spo2: 97, tempC: 36.9, gcs: 15, status: "concern" },
    history: [
      { q: "How has your urine output changed?", category: "presenting-complaint", a: "Barely any urine in the last 24 hours.", key: true },
      { q: "Any recent diarrhea or vomiting?", category: "presenting-complaint", a: "Yes, watery diarrhea for a week.", key: true },
      { q: "What medications are you on?", category: "medications", a: "Losartan, and I started ibuprofen for joint pain 3 days ago.", key: true },
      { q: "Any pain in your back or flanks?", category: "presenting-complaint", a: "No flank pain." },
      { q: "Any known kidney disease?", category: "past-medical", a: "No, kidneys were fine last checkup." },
    ],
    exam: [
      { system: "general", finding: "Dry mucous membranes, reduced skin turgor.", key: true },
      { system: "cardiovascular", finding: "Postural hypotension on standing.", key: true },
      { system: "abdominal", finding: "No suprapubic distension, no flank tenderness.", key: true },
    ],
    investigations: [
      { name: "Renal function panel", category: "biochemistry", indication: "Suspected AKI", turnaround: 30, result: "Creatinine 3.4 mg/dL (baseline 1.0), urea 98 mg/dL.", interpretation: "KDIGO stage 3 AKI.", diagnostic: true },
      { name: "Urinalysis", category: "urinalysis", indication: "Characterize AKI type", turnaround: 20, result: "Bland sediment, no casts, no protein.", interpretation: "Supports pre-renal cause over intrinsic renal disease.", diagnostic: true },
      { name: "Renal ultrasound", category: "ultrasound", indication: "Exclude obstruction", turnaround: 60, result: "No hydronephrosis, normal-sized kidneys.", interpretation: "Excludes post-renal (obstructive) cause.", diagnostic: true },
      { name: "Serum potassium", category: "biochemistry", indication: "Assess for life-threatening hyperkalemia", turnaround: 20, result: "6.1 mmol/L.", interpretation: "Hyperkalemia requiring urgent treatment.", diagnostic: true },
    ],
    redFlags: ["Hyperkalemia with ECG changes risk", "Anuria/oliguria", "NSAID + ACE-inhibitor/ARB combination in volume depletion"],
    referenceDifferentials: [
      { diagnosis: "Pre-renal acute kidney injury", rationale: "Volume depletion from diarrhea, compounded by ARB + NSAID reducing renal perfusion, bland urinalysis.", mustNotMiss: true },
      { diagnosis: "Acute tubular necrosis", rationale: "Could evolve from prolonged pre-renal insult if untreated.", mustNotMiss: true },
      { diagnosis: "Post-renal obstruction", rationale: "Excluded by ultrasound." },
    ],
    management: [
      { label: "Stop nephrotoxic drugs (NSAID, ARB) immediately", description: "Removes ongoing renal insult.", critical: true },
      { label: "Cautious IV isotonic fluid resuscitation", description: "Corrects pre-renal state; monitor for fluid overload.", critical: true },
      { label: "Treat hyperkalemia (calcium gluconate, insulin-dextrose, consider dialysis if refractory)", description: "Hyperkalemia at this level is immediately life-threatening.", critical: true },
      { label: "Continue ibuprofen for symptom control", description: "Continuing an NSAID worsens AKI and is unsafe.", unsafe: true },
      { label: "Give large empirical dose of IV contrast for a CT scan 'to be thorough'", description: "Unnecessary nephrotoxic contrast load in active AKI.", unsafe: true },
    ],
    criticalActions: ["Stop nephrotoxic drugs (NSAID, ARB) immediately", "Cautious IV isotonic fluid resuscitation", "Treat hyperkalemia (calcium gluconate, insulin-dextrose, consider dialysis if refractory)"],
    unsafeActions: ["Continue ibuprofen for symptom control", "Give large empirical dose of IV contrast for a CT scan 'to be thorough'"],
    prescriptionContext: {
      ageYears: 71, weightKg: 74, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "failure", hepaticFunction: "normal", currentMedications: ["losartan", "ibuprofen (to be stopped)"], diagnoses: ["acute kidney injury", "hyperkalemia"],
    },
    prescriptionReference: [
      { genericName: "calcium gluconate 10%", formulation: "IV injection", strength: "10 mL", route: "intravenous", frequency: "once, repeat if ECG changes persist", duration: "acute", indication: "Cardiac membrane stabilization in hyperkalemia" },
      { genericName: "insulin (regular) with dextrose", formulation: "IV injection", strength: "10 units insulin + 25g dextrose", route: "intravenous", frequency: "once, reassess K+", duration: "acute", indication: "Shift potassium intracellularly" },
      { genericName: "sodium chloride 0.9%", formulation: "IV infusion", strength: "isotonic", route: "intravenous", frequency: "cautious bolus then reassess", duration: "until euvolemic", indication: "Correct pre-renal AKI" },
    ],
    referenceDx: "Pre-renal acute kidney injury (KDIGO stage 3) with hyperkalemia",
    viva: [
      { stage: "case", prompt: "Why is the combination of an ARB and an NSAID particularly dangerous in volume depletion?", points: ["Both reduce glomerular perfusion/filtration pressure, compounding pre-renal injury"] },
      { stage: "case", prompt: "What urinalysis pattern supports a pre-renal rather than intrinsic renal cause?", points: ["Bland sediment without casts or significant protein"] },
    ],
    debrief: {
      pearls: ["Always ask about NSAID use in any AKI workup — it's a very common, reversible contributor.", "Treat life-threatening hyperkalemia before it's 'confirmed' by ECG changes if the level is critical."],
      references: ["KDIGO Clinical Practice Guideline for AKI"],
    },
  },

  {
    slug: "EDU-ID-001",
    title: "Burning Urination and Fever with Flank Pain",
    specialty: "Infectious Disease",
    subspecialty: "Urology",
    difficulty: "FOUNDATION",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE", "NURSING", "PHARMACY"],
    patientSex: "female",
    patientAgeBand: "25-29",
    chiefComplaint: "Burning urination, fever and right flank pain for 2 days",
    learningObjectives: ["Distinguish cystitis from pyelonephritis", "Select appropriate empirical antibiotics for pyelonephritis", "Recognize when urosepsis is developing"],
    presentation: "A 27-year-old woman presents with 2 days of dysuria, urinary frequency, fever, and new right flank pain.",
    initialVitals: { hr: 108, sbp: 108, dbp: 68, rr: 20, spo2: 97, tempC: 38.9, gcs: 15, status: "concern" },
    history: [
      { q: "Any burning or frequency with urination?", category: "presenting-complaint", a: "Yes, both, for 2 days.", key: true },
      { q: "Any back or flank pain?", category: "presenting-complaint", a: "Yes, right side, started yesterday.", key: true },
      { q: "Any nausea or vomiting?", category: "associated-symptoms", a: "Yes, vomited twice this morning." },
      { q: "Could you be pregnant?", category: "obstetric", a: "No, not pregnant." },
      { q: "Any prior urinary tract infections?", category: "past-medical", a: "Yes, a couple in the past, always cleared with antibiotics." },
    ],
    exam: [
      { system: "abdominal", finding: "Right-sided costovertebral angle tenderness.", key: true },
      { system: "general", finding: "Febrile, uncomfortable.", key: true },
      { system: "cardiovascular", finding: "Tachycardic, normotensive currently." },
    ],
    investigations: [
      { name: "Urinalysis", category: "urinalysis", indication: "Suspected UTI/pyelonephritis", turnaround: 20, result: "Leukocyte esterase +, nitrites +, WBC casts present.", interpretation: "WBC casts localize infection to the kidney — pyelonephritis, not simple cystitis.", diagnostic: true },
      { name: "Urine culture", category: "microbiology", indication: "Confirm organism and sensitivities", turnaround: 1440, result: "Pending — E. coli grown at 48h, sensitive to ceftriaxone.", interpretation: "Guides definitive antibiotic choice; don't delay empirical treatment." },
      { name: "CBC", category: "hematology", indication: "Assess systemic response", turnaround: 30, result: "WBC 15,600/uL.", interpretation: "Systemic inflammatory response, supports upper tract infection." },
      { name: "Renal ultrasound", category: "ultrasound", indication: "Exclude obstruction/abscess if not responding", turnaround: 60, result: "Not indicated at this stage — reserve for non-response to therapy or suspicion of obstruction.", interpretation: "Ordering routinely here adds no value.", distractor: true },
    ],
    redFlags: ["Fever with flank pain = upper tract involvement", "Vomiting limiting oral antibiotic tolerance", "Risk of progression to urosepsis"],
    referenceDifferentials: [
      { diagnosis: "Acute pyelonephritis", rationale: "Dysuria + fever + flank pain + WBC casts.", mustNotMiss: true },
      { diagnosis: "Uncomplicated cystitis", rationale: "Would lack flank pain, fever, and WBC casts." },
      { diagnosis: "Nephrolithiasis with secondary infection", rationale: "Consider if pain is colicky; imaging can clarify if not improving." },
    ],
    management: [
      { label: "Start empirical IV or oral antibiotics per local pyelonephritis protocol", description: "Timely antibiotics prevent progression to sepsis.", critical: true },
      { label: "IV fluids and antiemetics given vomiting", description: "Supports hydration and antibiotic tolerance." },
      { label: "Reassess for sepsis criteria (qSOFA)", description: "Flank pain + fever can progress rapidly to urosepsis.", critical: true },
      { label: "Treat as simple cystitis with 3-day oral course only", description: "Undertreats pyelonephritis, risking progression/relapse.", unsafe: true },
    ],
    criticalActions: ["Start empirical IV or oral antibiotics per local pyelonephritis protocol", "Reassess for sepsis criteria (qSOFA)"],
    unsafeActions: ["Treat as simple cystitis with 3-day oral course only"],
    prescriptionContext: {
      ageYears: 27, weightKg: 62, allergies: [], pregnancyStatus: "not-pregnant",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["acute pyelonephritis"],
    },
    prescriptionReference: [
      { genericName: "ceftriaxone", formulation: "IV injection", strength: "1 g", route: "intravenous", frequency: "once daily", duration: "step down to oral after 48-72h afebrile, total 7-14 days", indication: "Empirical pyelonephritis coverage" },
      { genericName: "ondansetron", formulation: "IV injection", strength: "4 mg", route: "intravenous", frequency: "PRN", duration: "as needed", indication: "Antiemetic" },
    ],
    referenceDx: "Acute pyelonephritis",
    viva: [
      { stage: "case", prompt: "What urinalysis finding distinguishes pyelonephritis from simple cystitis?", points: ["WBC casts, indicating renal tubular origin of the infection"] },
      { stage: "case", prompt: "What would prompt you to image the renal tract in this patient?", points: ["Failure to improve after 48-72h of appropriate antibiotics, suspected obstruction/stone, recurrent infection"] },
    ],
    debrief: {
      pearls: ["WBC casts on urinalysis localize infection to the kidney.", "Undertreating pyelonephritis as cystitis risks relapse and progression to urosepsis."],
      references: ["IDSA Guidelines for Uncomplicated Pyelonephritis"],
    },
  },

  {
    slug: "EDU-ID-002",
    title: "High Fever, Rash and Falling Platelet Count",
    specialty: "Infectious Disease",
    difficulty: "INTERMEDIATE",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE", "NURSING", "DIAGNOSTICS"],
    patientSex: "female",
    patientAgeBand: "20-24",
    chiefComplaint: "High fever for 8 days with rash and falling platelet count",
    learningObjectives: ["Recognize dengue warning signs", "Understand the critical/leak phase of dengue", "Avoid NSAIDs and unnecessary IV fluids overload in dengue"],
    presentation: "A 24-year-old woman presents with 8 days of high fever, now with a diffuse rash and easy bruising. Her platelet count is falling on serial testing.",
    initialVitals: { hr: 104, sbp: 100, dbp: 68, rr: 20, spo2: 97, tempC: 38.4, gcs: 15, status: "concern" },
    history: [
      { q: "How has the fever pattern been?", category: "presenting-complaint", a: "High fever for a week, today it actually came down but I feel worse.", key: true },
      { q: "Any bleeding — gums, nose, or in your stool?", category: "associated-symptoms", a: "My gums bled a little this morning.", key: true },
      { q: "Any abdominal pain?", category: "associated-symptoms", a: "Yes, upper abdominal pain since yesterday.", key: true },
      { q: "Any recent travel or mosquito exposure?", category: "social", a: "I live in an area with a lot of mosquitoes, no travel." },
      { q: "Are you taking anything for the fever?", category: "medications", a: "I've been taking ibuprofen for the fever.", key: true },
    ],
    exam: [
      { system: "skin", finding: "Diffuse maculopapular rash, petechiae on lower limbs.", key: true },
      { system: "abdominal", finding: "Mild hepatomegaly, tender.", key: true },
      { system: "cardiovascular", finding: "Narrow pulse pressure (26 mmHg), cool peripheries.", key: true },
    ],
    investigations: [
      { name: "CBC", category: "hematology", indication: "Suspected dengue", turnaround: 30, result: "Platelets 62,000/uL (falling from 140,000 two days ago), hematocrit rising 18% from baseline.", interpretation: "Rising hematocrit + falling platelets = plasma leakage, the hallmark of the critical phase.", diagnostic: true },
      { name: "NS1 antigen / dengue serology", category: "serology", indication: "Confirm dengue", turnaround: 120, result: "NS1 positive.", interpretation: "Confirms dengue infection.", diagnostic: true },
      { name: "Liver function tests", category: "biochemistry", indication: "Assess hepatic involvement", turnaround: 45, result: "AST/ALT mildly elevated.", interpretation: "Common in dengue, supportive rather than diagnostic." },
      { name: "Coagulation panel", category: "special", indication: "Assess bleeding risk", turnaround: 40, result: "Mildly prolonged PT, normal fibrinogen.", interpretation: "Monitor closely given active bleeding signs." },
    ],
    redFlags: ["Narrowing pulse pressure (plasma leak/shock)", "Rising hematocrit with falling platelets", "Mucosal bleeding", "Abdominal pain in defervescence = warning sign"],
    referenceDifferentials: [
      { diagnosis: "Dengue fever with warning signs", rationale: "Fever pattern, rash, bleeding, rising hematocrit with falling platelets, abdominal pain at defervescence.", mustNotMiss: true },
      { diagnosis: "Typhoid fever", rationale: "Can cause prolonged fever but doesn't explain thrombocytopenia/hematocrit rise pattern." },
      { diagnosis: "Leptospirosis", rationale: "Consider with fever + bleeding + exposure history; less consistent with this rash/hematocrit pattern.", mustNotMiss: true },
    ],
    management: [
      { label: "Careful isotonic IV fluid titration per dengue warning-signs protocol", description: "Avoid both under- and over-resuscitation during the critical leak phase.", critical: true },
      { label: "Stop NSAIDs immediately", description: "NSAIDs worsen bleeding risk and are contraindicated in dengue.", critical: true },
      { label: "Serial hematocrit and platelet monitoring", description: "Tracks plasma leak phase progression.", critical: true },
      { label: "Give large-volume IV fluid bolus liberally 'to be safe'", description: "Over-resuscitation in dengue can precipitate fluid overload and respiratory distress.", unsafe: true },
      { label: "Continue ibuprofen for fever control", description: "Contraindicated — increases bleeding and GI complication risk.", unsafe: true },
    ],
    criticalActions: ["Careful isotonic IV fluid titration per dengue warning-signs protocol", "Stop NSAIDs immediately", "Serial hematocrit and platelet monitoring"],
    unsafeActions: ["Give large-volume IV fluid bolus liberally 'to be safe'", "Continue ibuprofen for fever control"],
    prescriptionContext: {
      ageYears: 24, weightKg: 58, allergies: [], pregnancyStatus: "not-pregnant",
      renalFunction: "normal", hepaticFunction: "impaired", currentMedications: ["ibuprofen (to be stopped)"], diagnoses: ["dengue fever with warning signs"],
    },
    prescriptionReference: [
      { genericName: "paracetamol", formulation: "tablet", strength: "500 mg", route: "oral", frequency: "QID PRN, max 3g/day", duration: "as needed", indication: "Antipyretic — NSAIDs avoided in dengue" },
      { genericName: "sodium chloride 0.9%", formulation: "IV infusion", strength: "titrated per protocol", route: "intravenous", frequency: "per hematocrit/vitals response", duration: "critical phase (24-48h)", indication: "Plasma leak correction", monitoring: "Hourly vitals, serial hematocrit" },
    ],
    referenceDx: "Dengue fever with warning signs (critical phase)",
    viva: [
      { stage: "case", prompt: "Why is defervescence with new abdominal pain concerning in dengue, not reassuring?", points: ["Marks transition into the critical plasma-leak phase, not recovery"] },
      { stage: "drug", prompt: "Why are NSAIDs specifically avoided in dengue?", points: ["Increase bleeding risk (platelet dysfunction) and GI/renal complications"] },
    ],
    debrief: {
      pearls: ["Fever coming down is NOT always good news in dengue — watch for the critical phase.", "Rising hematocrit with falling platelets is the signature of plasma leakage."],
      references: ["WHO Dengue Guidelines for Diagnosis, Treatment, Prevention and Control"],
    },
  },

  {
    slug: "EDU-ENDO-003",
    title: "Unintentional Weight Loss, Palpitations and Heat Intolerance",
    specialty: "Endocrinology",
    difficulty: "FOUNDATION",
    acuity: "ROUTINE",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "female",
    patientAgeBand: "30-34",
    chiefComplaint: "Weight loss, palpitations, and heat intolerance over 2 months",
    learningObjectives: ["Recognize clinical features of hyperthyroidism", "Interpret thyroid function tests", "Screen for thyroid eye disease and atrial fibrillation risk"],
    presentation: "A 32-year-old woman presents with 2 months of unintentional weight loss despite increased appetite, palpitations, heat intolerance, and irritability.",
    initialVitals: { hr: 112, sbp: 138, dbp: 76, rr: 16, spo2: 99, tempC: 37.3, gcs: 15, status: "stable" },
    history: [
      { q: "Have you noticed any weight change?", category: "presenting-complaint", a: "Lost about 6 kg without trying, despite eating more.", key: true },
      { q: "Any heat intolerance or excess sweating?", category: "associated-symptoms", a: "Yes, I'm always too warm now.", key: true },
      { q: "Any tremor or palpitations?", category: "associated-symptoms", a: "Yes, my hands shake and my heart races.", key: true },
      { q: "Any change in bowel habits?", category: "review-of-systems", a: "More frequent, looser stools." },
      { q: "Any eye symptoms — bulging, irritation?", category: "review-of-systems", a: "My eyes have felt a bit gritty and look more prominent." , key: true},
      { q: "Any family history of thyroid disease?", category: "family", a: "My mother has a thyroid condition." },
    ],
    exam: [
      { system: "general", finding: "Fine tremor of outstretched hands, warm moist skin.", key: true },
      { system: "cardiovascular", finding: "Tachycardic, irregularly irregular pulse noted intermittently.", key: true },
      { system: "ophthalmic", finding: "Mild proptosis, lid retraction bilaterally.", key: true },
      { system: "general", finding: "Diffusely enlarged, non-tender thyroid gland with audible bruit.", key: true },
    ],
    investigations: [
      { name: "TSH", category: "biochemistry", indication: "Suspected thyrotoxicosis", turnaround: 90, result: "<0.01 mIU/L (suppressed).", interpretation: "Consistent with hyperthyroidism.", diagnostic: true },
      { name: "Free T4 / Free T3", category: "biochemistry", indication: "Confirm thyrotoxicosis", turnaround: 90, result: "Free T4 4.2 ng/dL (elevated), Free T3 elevated.", interpretation: "Overt hyperthyroidism.", diagnostic: true },
      { name: "TSH receptor antibodies (TRAb)", category: "serology", indication: "Confirm Graves' disease etiology", turnaround: 240, result: "Positive, high titer.", interpretation: "Confirms Graves' disease as the cause.", diagnostic: true },
      { name: "ECG", category: "ecg", indication: "Screen for atrial fibrillation", turnaround: 5, result: "Sinus tachycardia with occasional ectopics, no sustained AF captured.", interpretation: "Warrants ongoing rhythm monitoring given palpitations." },
    ],
    redFlags: ["Irregularly irregular pulse (possible AF)", "Signs of thyroid eye disease", "Risk of thyroid storm if untreated/stressed"],
    referenceDifferentials: [
      { diagnosis: "Graves' disease", rationale: "Diffuse goiter with bruit, proptosis, positive TRAb, suppressed TSH.", mustNotMiss: true },
      { diagnosis: "Toxic multinodular goiter", rationale: "Would show nodular rather than diffuse gland, TRAb typically negative." },
      { diagnosis: "Subacute thyroiditis", rationale: "Usually painful gland and self-limiting course, less consistent here." },
    ],
    management: [
      { label: "Start antithyroid medication (e.g. carbimazole)", description: "First-line therapy to reduce thyroid hormone synthesis.", critical: true },
      { label: "Start beta-blocker for symptom control", description: "Controls tachycardia/tremor while antithyroid drugs take effect.", critical: true },
      { label: "Refer to ophthalmology given eye findings", description: "Thyroid eye disease needs dedicated monitoring/management." },
      { label: "Withhold all treatment pending endocrinology appointment in 3 months", description: "Delays symptom control and risks cardiovascular/eye complications.", unsafe: true },
    ],
    criticalActions: ["Start antithyroid medication (e.g. carbimazole)", "Start beta-blocker for symptom control"],
    unsafeActions: ["Withhold all treatment pending endocrinology appointment in 3 months"],
    prescriptionContext: {
      ageYears: 32, weightKg: 58, allergies: [], pregnancyStatus: "not-pregnant",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["Graves' disease"],
    },
    prescriptionReference: [
      { genericName: "carbimazole", formulation: "tablet", strength: "20 mg", route: "oral", frequency: "once daily, titrate", duration: "12-18 months initial course", indication: "Thyroid hormone synthesis inhibition", monitoring: "TFTs every 4-6 weeks, CBC for agranulocytosis risk" },
      { genericName: "propranolol", formulation: "tablet", strength: "20 mg", route: "oral", frequency: "TDS", duration: "until euthyroid", indication: "Symptomatic adrenergic control" },
    ],
    referenceDx: "Graves' disease (hyperthyroidism)",
    viva: [
      { stage: "case", prompt: "What examination findings point specifically toward Graves' disease rather than another cause of hyperthyroidism?", points: ["Diffuse goiter with bruit, proptosis/lid retraction, positive TRAb"] },
      { stage: "drug", prompt: "What serious adverse effect must patients on carbimazole be warned about?", points: ["Agranulocytosis — seek urgent review for sore throat/fever"] },
    ],
    debrief: {
      pearls: ["Eye signs (proptosis, lid retraction) point specifically toward Graves' disease.", "Always warn patients starting carbimazole about agranulocytosis."],
      references: ["ATA Guidelines for Hyperthyroidism and Other Causes of Thyrotoxicosis"],
    },
  },

  {
    slug: "EDU-HEME-001",
    title: "Progressive Fatigue and Pallor in a Young Woman",
    specialty: "Hematology",
    difficulty: "FOUNDATION",
    acuity: "ROUTINE",
    learnerTracks: ["MEDICINE", "NURSING", "PUBLIC_HEALTH"],
    patientSex: "female",
    patientAgeBand: "20-24",
    chiefComplaint: "Progressive fatigue, breathlessness on exertion, and pallor over 3 months",
    learningObjectives: ["Work up microcytic anemia systematically", "Recognize iron deficiency anemia and identify its cause", "Understand indications for further GI workup"],
    presentation: "A 22-year-old woman presents with 3 months of progressive fatigue, exertional breathlessness, and pallor. She reports heavy menstrual periods.",
    initialVitals: { hr: 102, sbp: 108, dbp: 68, rr: 18, spo2: 98, tempC: 36.8, gcs: 15, status: "stable" },
    history: [
      { q: "How would you describe your periods?", category: "obstetric", a: "Very heavy, soaking a pad every hour on the heaviest days.", key: true },
      { q: "Any blood in your stool or dark stools?", category: "review-of-systems", a: "No, stools look normal." },
      { q: "Any dietary restrictions?", category: "social", a: "I'm vegetarian and don't eat much iron-rich food.", key: true },
      { q: "Any pica (craving ice, dirt, starch)?", category: "review-of-systems", a: "Actually yes, I've been chewing ice a lot recently.", key: true },
      { q: "Any prior history of anemia?", category: "past-medical", a: "Told once before I was borderline low." },
    ],
    exam: [
      { system: "general", finding: "Conjunctival pallor, pale nail beds, koilonychia (spoon nails).", key: true },
      { system: "cardiovascular", finding: "Tachycardic, soft flow murmur.", key: true },
      { system: "general", finding: "Angular stomatitis noted.", key: true },
    ],
    investigations: [
      { name: "CBC", category: "hematology", indication: "Suspected anemia", turnaround: 30, result: "Hb 7.8 g/dL, MCV 68 fL (microcytic).", interpretation: "Microcytic anemia.", diagnostic: true },
      { name: "Iron studies", category: "biochemistry", indication: "Characterize microcytic anemia", turnaround: 60, result: "Ferritin 6 ng/mL (low), TIBC elevated, transferrin saturation 8%.", interpretation: "Confirms iron deficiency anemia.", diagnostic: true },
      { name: "Peripheral smear", category: "pathology", indication: "Morphology review", turnaround: 60, result: "Microcytic, hypochromic RBCs, anisopoikilocytosis, occasional pencil cells.", interpretation: "Classic for iron deficiency." },
      { name: "Hemoglobin electrophoresis", category: "special", indication: "Exclude thalassemia trait as alternative cause of microcytosis", turnaround: 180, result: "Normal HbA2/HbF.", interpretation: "Excludes thalassemia trait, supports iron deficiency as sole cause." },
    ],
    redFlags: ["Hb <8 g/dL with tachycardia", "Pica (chewing ice) is a specific symptom of iron deficiency", "Need to identify and treat the underlying source of blood loss"],
    referenceDifferentials: [
      { diagnosis: "Iron deficiency anemia secondary to menorrhagia", rationale: "Low ferritin, high TIBC, heavy periods, koilonychia, pica.", mustNotMiss: true },
      { diagnosis: "Thalassemia trait", rationale: "Also microcytic but with normal/high ferritin and abnormal electrophoresis — excluded here." },
      { diagnosis: "Anemia of chronic disease", rationale: "Usually normocytic with high ferritin — pattern doesn't fit." },
    ],
    management: [
      { label: "Start oral iron replacement", description: "First-line for confirmed iron deficiency anemia.", critical: true },
      { label: "Refer to gynecology for menorrhagia workup/management", description: "Addresses the underlying cause, not just the anemia.", critical: true },
      { label: "Counsel on dietary iron sources and absorption (vitamin C co-ingestion)", description: "Supports oral therapy effectiveness." },
      { label: "Transfuse packed red cells routinely for all Hb <8", description: "Not automatically indicated in a hemodynamically stable, chronic, compensated anemia — oral iron is first-line unless symptomatic/unstable.", unsafe: true },
    ],
    criticalActions: ["Start oral iron replacement", "Refer to gynecology for menorrhagia workup/management"],
    unsafeActions: ["Transfuse packed red cells routinely for all Hb <8"],
    prescriptionContext: {
      ageYears: 22, weightKg: 55, allergies: [], pregnancyStatus: "not-pregnant",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["iron deficiency anemia"],
    },
    prescriptionReference: [
      { genericName: "ferrous sulfate", formulation: "tablet", strength: "325 mg (65 mg elemental iron)", route: "oral", frequency: "once daily on alternate days", duration: "3-6 months", indication: "Iron repletion", monitoring: "Repeat Hb/ferritin at 4-6 weeks" },
      { genericName: "tranexamic acid", formulation: "tablet", strength: "500 mg", route: "oral", frequency: "TDS during menses", duration: "during heavy flow days", indication: "Reduce menstrual blood loss" },
    ],
    referenceDx: "Iron deficiency anemia secondary to menorrhagia",
    viva: [
      { stage: "case", prompt: "What iron study pattern confirms iron deficiency rather than thalassemia trait?", points: ["Low ferritin with elevated TIBC; thalassemia trait typically has normal/high ferritin"] },
      { stage: "case", prompt: "Why is pica a clinically useful symptom to ask about?", points: ["Relatively specific for iron deficiency, especially ice craving (pagophagia)"] },
    ],
    debrief: {
      pearls: ["Pica, especially pagophagia (ice craving), is a distinctive clue for iron deficiency.", "Always look for and address the source of blood loss, not just replace iron."],
      references: ["WHO Guideline on Iron Deficiency Anaemia"],
    },
  },

  {
    slug: "EDU-EM-SEPSIS-001",
    title: "Fever, Confusion and Low Blood Pressure in a Nursing Home Resident",
    specialty: "Critical Care",
    difficulty: "EXPERT",
    acuity: "EMERGENCY",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "female",
    patientAgeBand: "80-84",
    chiefComplaint: "Fever, new confusion and low blood pressure",
    learningObjectives: ["Recognize sepsis and septic shock early", "Apply the Sepsis Six / hour-1 bundle", "Identify a likely source to guide antibiotics"],
    presentation: "An 84-year-old nursing home resident with a urinary catheter is brought in with a day of fever, new confusion, and today, low blood pressure noted by staff.",
    initialVitals: { hr: 118, sbp: 82, dbp: 50, rr: 26, spo2: 90, tempC: 39.3, gcs: 13, status: "critical" },
    vitalsTimeline: [
      { hr: 118, sbp: 82, dbp: 50, rr: 26, spo2: 90, tempC: 39.3, gcs: 13, status: "critical", label: "On arrival" },
      { hr: 128, sbp: 74, dbp: 44, rr: 30, spo2: 88, tempC: 39.6, gcs: 12, status: "critical", label: "T+20 min (if bundle delayed)" },
    ],
    history: [
      { q: "Does she have a urinary catheter?", category: "past-medical", a: "Yes, long-term catheter for 8 months.", key: true },
      { q: "Any recent change in urine — cloudy, foul-smelling?", category: "presenting-complaint", a: "Staff noted cloudy, foul urine yesterday.", key: true },
      { q: "Any cough or respiratory symptoms?", category: "review-of-systems", a: "No cough noted." },
      { q: "Any skin breakdown or pressure sores?", category: "review-of-systems", a: "One stage 1 pressure sore on sacrum, not infected-looking." },
      { q: "What is her baseline mental status?", category: "past-medical", a: "Normally alert and oriented, this confusion is new.", key: true },
    ],
    exam: [
      { system: "mental-status", finding: "Confused, GCS 13, new from baseline.", key: true },
      { system: "abdominal", finding: "Suprapubic tenderness, catheter draining cloudy, foul urine.", key: true },
      { system: "general", finding: "Warm peripheries initially, capillary refill 3 seconds.", key: true },
      { system: "cardiovascular", finding: "Tachycardic, hypotensive.", key: true },
    ],
    investigations: [
      { name: "Serum lactate", category: "biochemistry", indication: "Suspected sepsis", turnaround: 15, result: "4.2 mmol/L.", interpretation: "Elevated lactate supports tissue hypoperfusion — part of Sepsis-3 criteria.", diagnostic: true },
      { name: "Blood cultures (x2)", category: "microbiology", indication: "Before antibiotics if it doesn't delay treatment", turnaround: 2880, result: "Pending; grew E. coli at 36h.", interpretation: "Send before first antibiotic dose ideally, but never delay antibiotics beyond ~45 minutes to do so." },
      { name: "Urinalysis + urine culture", category: "urinalysis", indication: "Likely source given catheter", turnaround: 60, result: "Pyuria, nitrites positive; culture later grew E. coli.", interpretation: "Confirms catheter-associated UTI as the likely septic source.", diagnostic: true },
      { name: "CBC and renal function", category: "hematology", indication: "Assess organ dysfunction", turnaround: 30, result: "WBC 19,400/uL, creatinine 1.9 mg/dL (new rise from baseline 0.9).", interpretation: "New organ dysfunction — meets sepsis criteria." },
    ],
    redFlags: ["qSOFA >=2 (altered mentation, RR>=22, SBP<=100)", "Lactate >2 mmol/L", "New organ dysfunction (renal)", "Hypotension not responding quickly = septic shock risk"],
    referenceDifferentials: [
      { diagnosis: "Sepsis secondary to catheter-associated urinary tract infection", rationale: "Fever, confusion, hypotension, elevated lactate, pyuria, indwelling catheter.", mustNotMiss: true },
      { diagnosis: "Septic shock", rationale: "If hypotension persists despite adequate fluid resuscitation — must reassess after bundle.", mustNotMiss: true },
      { diagnosis: "Aspiration pneumonia", rationale: "Common alternative source in elderly patients; less supported here given clear urinary source." },
    ],
    management: [
      { label: "Obtain lactate and blood cultures immediately", description: "Core to the Sepsis Six / hour-1 bundle.", critical: true },
      { label: "Give broad-spectrum IV antibiotics within 1 hour", description: "Every hour of delay increases mortality in sepsis.", critical: true },
      { label: "Give IV crystalloid fluid bolus (30 mL/kg) for hypotension/elevated lactate", description: "Core resuscitation step.", critical: true },
      { label: "Start vasopressors if hypotension persists after adequate fluids", description: "Defines septic shock management if fluid-refractory.", critical: true },
      { label: "Replace the urinary catheter as the first priority before antibiotics", description: "Delays life-saving antibiotics; source control matters but never before the hour-1 bundle.", unsafe: true },
      { label: "Wait for blood culture results before starting antibiotics", description: "Dangerous delay — empirical antibiotics must not wait for culture confirmation.", unsafe: true },
    ],
    criticalActions: ["Obtain lactate and blood cultures immediately", "Give broad-spectrum IV antibiotics within 1 hour", "Give IV crystalloid fluid bolus (30 mL/kg) for hypotension/elevated lactate"],
    unsafeActions: ["Replace the urinary catheter as the first priority before antibiotics", "Wait for blood culture results before starting antibiotics"],
    prescriptionContext: {
      ageYears: 84, weightKg: 58, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "impaired", hepaticFunction: "normal", currentMedications: [], diagnoses: ["sepsis secondary to catheter-associated UTI"],
    },
    prescriptionReference: [
      { genericName: "piperacillin-tazobactam", formulation: "IV injection", strength: "4.5 g", route: "intravenous", frequency: "every 8 hours (renally adjusted)", duration: "7-10 days, reassess with cultures", indication: "Broad-spectrum empirical sepsis coverage", monitoring: "Renal function, clinical response" },
      { genericName: "norepinephrine", formulation: "IV infusion", strength: "titrated", route: "intravenous (central preferred)", frequency: "continuous, titrate to MAP >=65", duration: "until hemodynamically stable", indication: "Vasopressor support in fluid-refractory septic shock", monitoring: "Continuous BP monitoring" },
    ],
    referenceDx: "Sepsis secondary to catheter-associated urinary tract infection",
    viva: [
      { stage: "emergency", prompt: "Walk me through the hour-1 sepsis bundle for this patient.", points: ["Lactate, blood cultures before antibiotics if feasible, broad-spectrum antibiotics, 30mL/kg crystalloid, vasopressors if needed for MAP<65"] },
      { stage: "emergency", prompt: "Why not delay antibiotics to replace the catheter first?", points: ["Antibiotic delay directly increases mortality; source control is important but sequenced after/alongside, not before, antibiotics"] },
    ],
    debrief: {
      pearls: ["New confusion in an elderly patient is often the earliest sign of sepsis.", "Every hour of antibiotic delay in septic shock measurably increases mortality — don't wait for cultures."],
      references: ["Surviving Sepsis Campaign Guidelines"],
    },
  },
];
