import type { CaseDef } from "../builder";

export const pedsObgynEmergencyCases: CaseDef[] = [
  {
    slug: "EDU-PEDS-001",
    title: "Lethargic Toddler With Vomiting and Diarrhea",
    specialty: "Pediatrics",
    difficulty: "FOUNDATION",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "female",
    patientAgeBand: "1-4",
    patientAgeExact: 2,
    chiefComplaint: "Vomiting and watery diarrhea for 2 days, now lethargic",
    learningObjectives: ["Assess dehydration severity in a child", "Choose appropriate rehydration route (oral vs IV)", "Recognize red flags requiring urgent IV fluids"],
    presentation: "A 2-year-old girl is brought in by her mother with 2 days of vomiting and watery diarrhea, poor oral intake, and today appears unusually lethargic with fewer wet diapers.",
    initialVitals: { hr: 152, sbp: 84, dbp: 52, rr: 32, spo2: 97, tempC: 37.8, gcs: 14, status: "critical" },
    history: [
      { q: "How many wet diapers in the last 24 hours?", category: "presenting-complaint", a: "Only one, usually she has 5-6.", key: true },
      { q: "Is she able to keep fluids down?", category: "presenting-complaint", a: "No, vomits almost everything.", key: true },
      { q: "Any blood in the stool?", category: "review-of-systems", a: "No blood, just watery." },
      { q: "How is her activity level?", category: "presenting-complaint", a: "Very lethargic, not playing at all today.", key: true },
      { q: "Any fever?", category: "associated-symptoms", a: "Mild fever." },
    ],
    exam: [
      { system: "general", finding: "Lethargic, sunken eyes, dry mucous membranes.", key: true },
      { system: "general", finding: "Skin pinch (turgor) returns very slowly (>2 seconds).", key: true },
      { system: "pediatric", finding: "Sunken anterior fontanelle.", key: true },
      { system: "cardiovascular", finding: "Tachycardic, weak peripheral pulses, capillary refill 3-4 seconds.", key: true },
    ],
    investigations: [
      { name: "Point-of-care glucose", category: "biochemistry", indication: "Exclude hypoglycemia in an unwell child", turnaround: 1, result: "58 mg/dL (low-normal).", interpretation: "Monitor and correct if it falls further; not yet critically low.", diagnostic: true },
      { name: "Serum electrolytes", category: "biochemistry", indication: "Assess for hyponatremic/hypernatremic dehydration", turnaround: 30, result: "Sodium 148 mmol/L (mild hypernatremia), potassium 3.3 mmol/L.", interpretation: "Guides careful, gradual fluid correction to avoid rapid sodium shifts.", diagnostic: true },
      { name: "Venous blood gas", category: "abg-vbg", indication: "Assess for metabolic acidosis from dehydration", turnaround: 15, result: "pH 7.28, HCO3 15 mmol/L.", interpretation: "Metabolic acidosis consistent with significant dehydration.", diagnostic: true },
      { name: "Stool microscopy/culture", category: "microbiology", indication: "Identify causative organism", turnaround: 1440, result: "Pending.", interpretation: "Useful for epidemiology, does not change immediate rehydration priority." },
    ],
    redFlags: ["Lethargy + sunken fontanelle + delayed capillary refill = severe dehydration", "Hypernatremia requires careful, slow fluid correction", "Reduced urine output"],
    referenceDifferentials: [
      { diagnosis: "Severe dehydration secondary to acute gastroenteritis", rationale: "Lethargy, sunken eyes/fontanelle, delayed skin turgor and capillary refill, reduced urine output.", mustNotMiss: true },
      { diagnosis: "Sepsis", rationale: "Must remain on the differential in any lethargic febrile toddler — reassess if not improving with rehydration.", mustNotMiss: true },
      { diagnosis: "Diabetic ketoacidosis (new-onset)", rationale: "Consider in any unwell child with vomiting/acidosis; glucose here argues against it." },
    ],
    management: [
      { label: "IV isotonic fluid bolus (10-20 mL/kg) given signs of severe dehydration", description: "Oral rehydration is inappropriate once a child is this lethargic/unable to tolerate fluids.", critical: true },
      { label: "Reassess perfusion and mental status after each bolus", description: "Titrate further therapy to response." , critical: true},
      { label: "Correct hypernatremia gradually over 48 hours, not rapidly", description: "Rapid sodium correction in hypernatremic dehydration risks cerebral edema.", critical: true },
      { label: "Give only oral rehydration solution and send home", description: "Inappropriate for a lethargic child with signs of severe dehydration who cannot tolerate oral intake.", unsafe: true },
      { label: "Rapidly correct sodium to normal within a few hours using hypotonic fluids", description: "Risk of cerebral edema from overly rapid osmotic shift.", unsafe: true },
    ],
    criticalActions: ["IV isotonic fluid bolus (10-20 mL/kg) given signs of severe dehydration", "Reassess perfusion and mental status after each bolus", "Correct hypernatremia gradually over 48 hours, not rapidly"],
    unsafeActions: ["Give only oral rehydration solution and send home", "Rapidly correct sodium to normal within a few hours using hypotonic fluids"],
    prescriptionContext: {
      ageYears: 2, weightKg: 12, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["severe dehydration", "acute gastroenteritis"],
    },
    prescriptionReference: [
      { genericName: "sodium chloride 0.9%", formulation: "IV infusion", strength: "10-20 mL/kg bolus", route: "intravenous", frequency: "reassess after each bolus", duration: "acute resuscitation, then maintenance + deficit over 48h", indication: "Severe dehydration correction", monitoring: "Hourly vitals, repeat electrolytes at 6-8h" },
      { genericName: "ondansetron", formulation: "oral dissolving tablet", strength: "2 mg", route: "oral", frequency: "once, weight-based", duration: "single dose to allow oral trial", indication: "Antiemetic to support rehydration once stabilized" },
    ],
    referenceDx: "Severe (hypernatremic) dehydration secondary to acute gastroenteritis",
    viva: [
      { stage: "case", prompt: "Why must hypernatremic dehydration be corrected slowly?", points: ["Rapid correction causes fluid shift into brain cells, risking cerebral edema and seizures"] },
      { stage: "case", prompt: "What examination findings pushed you from 'some dehydration' to 'severe dehydration' here?", points: ["Lethargy, sunken fontanelle, delayed capillary refill, delayed skin turgor"] },
    ],
    debrief: {
      pearls: ["A lethargic, poorly perfused child needs IV fluids, not oral rehydration — reassess the plan as severity changes.", "Hypernatremic dehydration must be corrected slowly to avoid cerebral edema."],
      references: ["WHO Guidelines for the Management of Diarrhoea in Children", "AAP Clinical Practice Guideline: Managing Acute Gastroenteritis"],
    },
  },

  {
    slug: "EDU-PEDS-002",
    title: "Infant With Rapid Breathing and Chest Indrawing",
    specialty: "Pediatrics",
    subspecialty: "Pulmonology",
    difficulty: "INTERMEDIATE",
    acuity: "EMERGENCY",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "male",
    patientAgeBand: "0-1",
    patientAgeExact: 0,
    chiefComplaint: "Fast breathing, chest indrawing and poor feeding for 1 day",
    learningObjectives: ["Recognize signs of severe respiratory distress in infants", "Diagnose bronchiolitis and differentiate from pneumonia/asthma", "Apply supportive management principles for infant respiratory distress"],
    presentation: "A 6-month-old boy presents with 1 day of rapid breathing, audible wheeze, and difficulty feeding, following 2 days of runny nose and mild cough.",
    initialVitals: { hr: 168, sbp: 78, dbp: 48, rr: 64, spo2: 89, tempC: 38.2, gcs: 15, status: "critical" },
    history: [
      { q: "Has he been feeding normally?", category: "presenting-complaint", a: "Barely feeding, gets too breathless to finish a bottle.", key: true },
      { q: "Any preceding cold symptoms?", category: "presenting-complaint", a: "Runny nose and mild cough for 2 days before this.", key: true },
      { q: "Any similar episodes before?", category: "past-medical", a: "No, first time." },
      { q: "Any prematurity or heart/lung conditions?", category: "past-medical", a: "Born at 34 weeks, otherwise healthy.", key: true },
      { q: "Any blue color around lips?", category: "presenting-complaint", a: "Mother noticed slight blueness around his lips this morning.", key: true },
    ],
    exam: [
      { system: "respiratory", finding: "Marked subcostal and intercostal retractions, nasal flaring, expiratory wheeze bilaterally.", key: true },
      { system: "general", finding: "Perioral cyanosis, visibly tiring.", key: true },
      { system: "general", finding: "Poor feeding, mild dehydration signs.", key: true },
      { system: "cardiovascular", finding: "Tachycardic, otherwise normal heart sounds." },
    ],
    investigations: [
      { name: "Pulse oximetry (continuous)", category: "special", indication: "Assess hypoxia severity", turnaround: 1, result: "SpO2 89% on room air.", interpretation: "Significant hypoxia requiring oxygen therapy.", diagnostic: true },
      { name: "Nasopharyngeal viral panel (RSV)", category: "microbiology", indication: "Confirm bronchiolitis etiology", turnaround: 120, result: "RSV positive.", interpretation: "Confirms RSV bronchiolitis." },
      { name: "Chest X-ray", category: "xray", indication: "Only if diagnosis unclear or not improving as expected", turnaround: 20, result: "Hyperinflation with patchy atelectasis, no focal consolidation.", interpretation: "Consistent with bronchiolitis, not indicated routinely but reasonable here given severity.", },
      { name: "Blood/sputum culture and routine antibiotics workup", category: "microbiology", indication: "Bacterial pneumonia workup", turnaround: 1440, result: "Not indicated as first step — clinical picture is classic viral bronchiolitis.", interpretation: "Ordering broad bacterial workup here adds little value and delays supportive care.", distractor: true },
    ],
    redFlags: ["SpO2 <90%", "Grunting, marked retractions, nasal flaring", "Poor feeding/dehydration in an infant", "Apnea risk especially if ex-premature"],
    referenceDifferentials: [
      { diagnosis: "Acute bronchiolitis (RSV)", rationale: "Preceding coryza, wheeze, age <12 months, hypoxia, positive RSV panel.", mustNotMiss: true },
      { diagnosis: "Bacterial pneumonia", rationale: "Consider if focal consolidation or high fever with toxicity; X-ray pattern here favors bronchiolitis." },
      { diagnosis: "Congenital heart disease with decompensation", rationale: "Must remain on differential in an infant with respiratory distress and cyanosis, especially if not fitting the typical bronchiolitis course.", mustNotMiss: true },
    ],
    management: [
      { label: "Supplemental oxygen to target SpO2 >=90-92%", description: "Corrects hypoxia — a cornerstone of bronchiolitis supportive care.", critical: true },
      { label: "Nasal suctioning and upright positioning", description: "Reduces work of breathing by clearing upper airway secretions.", critical: true },
      { label: "Assess hydration and consider NG/IV fluids if feeding inadequate", description: "Prevents dehydration when oral intake is compromised.", critical: true },
      { label: "Give nebulized bronchodilators (salbutamol) routinely", description: "Not routinely recommended in bronchiolitis — limited evidence of benefit and can cause harm without proven improvement.", unsafe: true },
      { label: "Give empirical broad-spectrum antibiotics for presumed bacterial pneumonia", description: "Not indicated for classic viral bronchiolitis without evidence of bacterial infection.", unsafe: true },
    ],
    criticalActions: ["Supplemental oxygen to target SpO2 >=90-92%", "Nasal suctioning and upright positioning", "Assess hydration and consider NG/IV fluids if feeding inadequate"],
    unsafeActions: ["Give nebulized bronchodilators (salbutamol) routinely", "Give empirical broad-spectrum antibiotics for presumed bacterial pneumonia"],
    prescriptionContext: {
      ageYears: 0, weightKg: 7, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["acute bronchiolitis"],
    },
    prescriptionReference: [
      { genericName: "oxygen", formulation: "nasal cannula/head box", strength: "titrated", route: "inhalation", frequency: "continuous", duration: "until SpO2 stable >92% in air", indication: "Hypoxia correction", monitoring: "Continuous pulse oximetry" },
      { genericName: "normal saline nasal drops", formulation: "nasal drops", strength: "0.9%", route: "intranasal", frequency: "before feeds and suctioning", duration: "supportive, during illness", indication: "Secretion clearance support" },
    ],
    referenceDx: "Acute RSV bronchiolitis with hypoxia",
    viva: [
      { stage: "case", prompt: "Why are bronchodilators not routinely recommended in bronchiolitis, unlike asthma?", points: ["Evidence shows no consistent benefit in bronchiolitis pathophysiology (mucus plugging/edema, not primarily bronchospasm)"] },
      { stage: "case", prompt: "What features here would make you worried about impending respiratory failure?", points: ["Marked retractions, grunting, cyanosis, tiring/exhaustion, falling SpO2"] },
    ],
    debrief: {
      pearls: ["Bronchiolitis management is largely supportive (oxygen, suctioning, hydration) — resist reflexively reaching for bronchodilators/antibiotics.", "Ex-premature infants have a higher apnea risk with bronchiolitis."],
      references: ["AAP Clinical Practice Guideline: Bronchiolitis"],
    },
  },

  {
    slug: "EDU-OBGYN-001",
    title: "Severe Headache and High Blood Pressure at 34 Weeks",
    specialty: "Obstetrics",
    difficulty: "ADVANCED",
    acuity: "EMERGENCY",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "female",
    patientAgeBand: "25-29",
    chiefComplaint: "Severe headache and visual disturbance at 34 weeks gestation",
    learningObjectives: ["Diagnose preeclampsia with severe features", "Manage seizure prophylaxis and BP control safely in pregnancy", "Know indications for urgent delivery in severe preeclampsia"],
    presentation: "A 27-year-old woman, G2P1 at 34 weeks gestation, presents with a severe headache, visual spots, and epigastric pain over the last few hours.",
    initialVitals: { hr: 96, sbp: 172, dbp: 114, rr: 20, spo2: 97, tempC: 36.9, gcs: 15, status: "critical" },
    history: [
      { q: "Any headache, visual changes, or seeing spots?", category: "presenting-complaint", a: "Yes, bad headache and I keep seeing flashing spots.", key: true },
      { q: "Any upper abdominal pain?", category: "presenting-complaint", a: "Yes, pain under my right ribs.", key: true },
      { q: "Any swelling in your hands or face?", category: "review-of-systems", a: "Yes, my hands and face have swollen up in the last few days.", key: true },
      { q: "Was your blood pressure normal earlier in pregnancy?", category: "obstetric", a: "Yes, normal until this week.", key: true },
      { q: "Any history of high blood pressure before pregnancy?", category: "past-medical", a: "No prior history." },
    ],
    exam: [
      { system: "obstetric", finding: "Fundal height consistent with 34 weeks, fetal heart rate 145 bpm, reactive.", key: true },
      { system: "general", finding: "Facial and hand edema, brisk patellar reflexes (hyperreflexia).", key: true },
      { system: "abdominal", finding: "Right upper quadrant/epigastric tenderness.", key: true },
      { system: "cardiovascular", finding: "Severely elevated blood pressure confirmed on repeat measurement.", key: true },
    ],
    investigations: [
      { name: "Urine protein:creatinine ratio", category: "urinalysis", indication: "Confirm proteinuria for preeclampsia diagnosis", turnaround: 45, result: "0.6 (elevated, >0.3 threshold).", interpretation: "Significant proteinuria, supports preeclampsia diagnosis.", diagnostic: true },
      { name: "Liver function tests", category: "biochemistry", indication: "Screen for HELLP syndrome", turnaround: 45, result: "AST/ALT mildly elevated.", interpretation: "Hepatic involvement — screen further for HELLP.", diagnostic: true },
      { name: "CBC with platelet count", category: "hematology", indication: "Screen for HELLP syndrome", turnaround: 30, result: "Platelets 98,000/uL (low), hemolysis markers pending.", interpretation: "Thrombocytopenia raises concern for HELLP syndrome.", diagnostic: true },
      { name: "Uric acid", category: "biochemistry", indication: "Supportive marker of preeclampsia severity", turnaround: 45, result: "Elevated.", interpretation: "Supportive but not diagnostic alone." },
    ],
    redFlags: ["SBP >=160 or DBP >=110 = severe range, urgent treatment needed", "Headache/visual symptoms = risk of eclamptic seizure", "Falling platelets/rising LFTs = possible HELLP syndrome"],
    referenceDifferentials: [
      { diagnosis: "Preeclampsia with severe features", rationale: "New severe-range hypertension after 20 weeks + proteinuria + headache/visual symptoms + epigastric pain.", mustNotMiss: true },
      { diagnosis: "HELLP syndrome", rationale: "Must actively screen for given thrombocytopenia and elevated LFTs — a severe preeclampsia variant.", mustNotMiss: true },
      { diagnosis: "Chronic hypertension alone", rationale: "Excluded by new onset with proteinuria and severe features after previously normal BP." },
    ],
    management: [
      { label: "Start IV magnesium sulfate for seizure prophylaxis", description: "Reduces risk of progression to eclampsia in severe preeclampsia.", critical: true },
      { label: "Start IV antihypertensive (e.g. labetalol) to bring BP to a safe range", description: "Severe-range BP requires urgent, controlled reduction.", critical: true },
      { label: "Urgent obstetric assessment for timing of delivery", description: "Delivery is the definitive treatment for severe preeclampsia once maternal/fetal status assessed.", critical: true },
      { label: "Give an ACE inhibitor to control blood pressure", description: "ACE inhibitors are contraindicated in pregnancy (teratogenic/fetotoxic).", unsafe: true },
      { label: "Discharge home with oral antihypertensives and outpatient follow-up in 1 week", description: "Unsafe — severe features require inpatient stabilization and urgent delivery planning.", unsafe: true },
    ],
    criticalActions: ["Start IV magnesium sulfate for seizure prophylaxis", "Start IV antihypertensive (e.g. labetalol) to bring BP to a safe range", "Urgent obstetric assessment for timing of delivery"],
    unsafeActions: ["Give an ACE inhibitor to control blood pressure", "Discharge home with oral antihypertensives and outpatient follow-up in 1 week"],
    prescriptionContext: {
      ageYears: 27, weightKg: 78, allergies: [], pregnancyStatus: "pregnant",
      renalFunction: "normal", hepaticFunction: "impaired", currentMedications: [], diagnoses: ["preeclampsia with severe features"],
    },
    prescriptionReference: [
      { genericName: "magnesium sulfate", formulation: "IV infusion", strength: "4g loading then 1g/hr", route: "intravenous", frequency: "loading dose then continuous infusion", duration: "24h post-delivery or until stable", indication: "Eclampsia seizure prophylaxis", monitoring: "Reflexes, respiratory rate, urine output (magnesium toxicity risk)" },
      { genericName: "labetalol", formulation: "IV injection", strength: "20 mg, titrate", route: "intravenous", frequency: "every 10-20 min as needed", duration: "until BP controlled", indication: "Acute severe hypertension control in pregnancy" },
    ],
    referenceDx: "Preeclampsia with severe features (34 weeks gestation)",
    viva: [
      { stage: "case", prompt: "Why is magnesium sulfate given here, and what must you monitor for toxicity?", points: ["Seizure prophylaxis; monitor deep tendon reflexes, respiratory rate, urine output"] },
      { stage: "drug", prompt: "Why are ACE inhibitors avoided in this patient?", points: ["Teratogenic/fetotoxic — associated with fetal renal damage and other anomalies"] },
    ],
    debrief: {
      pearls: ["Headache and visual symptoms in preeclampsia signal imminent eclampsia risk — treat urgently.", "Delivery is the only definitive cure for preeclampsia; timing balances maternal and fetal risk."],
      references: ["ACOG Practice Bulletin: Gestational Hypertension and Preeclampsia"],
    },
  },

  {
    slug: "EDU-OBGYN-002",
    title: "Heavy Vaginal Bleeding Immediately After Delivery",
    specialty: "Obstetrics",
    difficulty: "EXPERT",
    acuity: "EMERGENCY",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "female",
    patientAgeBand: "30-34",
    chiefComplaint: "Heavy vaginal bleeding 20 minutes after vaginal delivery",
    learningObjectives: ["Apply the 4 T's framework for postpartum hemorrhage causes", "Sequence uterotonic and mechanical management", "Recognize hemorrhagic shock early"],
    presentation: "A 32-year-old woman, 20 minutes after an uncomplicated vaginal delivery of a healthy infant, is noted to have continuous heavy vaginal bleeding soaking through pads rapidly.",
    initialVitals: { hr: 128, sbp: 88, dbp: 54, rr: 24, spo2: 95, tempC: 36.8, gcs: 14, status: "critical" },
    vitalsTimeline: [
      { hr: 128, sbp: 88, dbp: 54, rr: 24, spo2: 95, tempC: 36.8, gcs: 14, status: "critical", label: "At recognition" },
      { hr: 140, sbp: 76, dbp: 46, rr: 28, spo2: 92, tempC: 36.6, gcs: 13, status: "critical", label: "T+10 min (if uncontrolled)" },
    ],
    history: [
      { q: "How much blood has been lost, estimated?", category: "presenting-complaint", a: "Nursing staff estimate over 700 mL and rising quickly.", key: true },
      { q: "Was the placenta delivered completely?", category: "obstetric", a: "Yes, delivered complete on inspection.", key: true },
      { q: "How long was the labor, and was oxytocin used?", category: "obstetric", a: "Prolonged second stage, oxytocin augmentation was used.", key: true },
      { q: "Any known bleeding disorders?", category: "past-medical", a: "None known." },
      { q: "Any perineal or vaginal trauma noted?", category: "obstetric", a: "No obvious laceration seen so far on initial look." , key: true},
    ],
    exam: [
      { system: "abdominal", finding: "Uterus soft ('boggy'), poorly contracted, fundus difficult to palpate distinctly.", key: true },
      { system: "general", finding: "Pale, diaphoretic, appears anxious.", key: true },
      { system: "cardiovascular", finding: "Tachycardic, hypotensive, delayed capillary refill.", key: true },
      { system: "obstetric", finding: "Continuous trickle of bright red blood from introitus, no obvious laceration on initial inspection." },
    ],
    investigations: [
      { name: "CBC and coagulation panel (STAT)", category: "hematology", indication: "Assess blood loss severity and coagulopathy", turnaround: 20, result: "Hb dropping serially, coagulation studies pending.", interpretation: "Confirms significant ongoing blood loss; guides transfusion decisions.", diagnostic: true },
      { name: "Group and crossmatch (STAT)", category: "hematology", indication: "Prepare for transfusion", turnaround: 20, result: "2 units crossmatched and available.", interpretation: "Essential preparation given ongoing hemorrhage.", diagnostic: true },
      { name: "Bedside uterine and pelvic examination", category: "special", indication: "Identify cause per 4 T's (Tone, Trauma, Tissue, Thrombin)", turnaround: 5, result: "Boggy, atonic uterus; no retained tissue or laceration found on exam.", interpretation: "Confirms uterine atony as the primary cause.", diagnostic: true },
    ],
    redFlags: ["Blood loss >500mL vaginal delivery = PPH by definition, act immediately", "Boggy uterus = atony, the most common cause", "Signs of hemorrhagic shock (tachycardia, hypotension)"],
    referenceDifferentials: [
      { diagnosis: "Postpartum hemorrhage due to uterine atony", rationale: "Boggy uterus, prolonged labor with oxytocin augmentation (risk factor), complete placenta, no laceration found.", mustNotMiss: true },
      { diagnosis: "Retained placental tissue", rationale: "Excluded here as placenta was complete on inspection — but must always be actively checked (the 'Tissue' T)." },
      { diagnosis: "Genital tract trauma (laceration)", rationale: "Must actively exclude with careful inspection (the 'Trauma' T) — not found on initial look, reassess if bleeding persists despite atony treatment.", mustNotMiss: true },
    ],
    management: [
      { label: "Bimanual uterine massage immediately", description: "First-line mechanical response to uterine atony.", critical: true },
      { label: "Give IV oxytocin as first-line uterotonic", description: "First-line pharmacologic treatment for atony.", critical: true },
      { label: "Escalate to second-line uterotonics (e.g. IM carboprost or misoprostol) if atony persists", description: "Sequenced escalation for ongoing atony.", critical: true },
      { label: "Establish large-bore IV access and begin fluid/blood resuscitation", description: "Addresses hemorrhagic shock in parallel with the source control.", critical: true },
      { label: "Wait and observe for 30 minutes before any intervention, expecting spontaneous resolution", description: "Dangerous delay — PPH from atony requires immediate action, not observation.", unsafe: true },
      { label: "Give an ergometrine-containing uterotonic without checking blood pressure", description: "Ergometrine is contraindicated/risky in hypertension and should be used cautiously with BP monitoring.", unsafe: true },
    ],
    criticalActions: ["Bimanual uterine massage immediately", "Give IV oxytocin as first-line uterotonic", "Establish large-bore IV access and begin fluid/blood resuscitation"],
    unsafeActions: ["Wait and observe for 30 minutes before any intervention, expecting spontaneous resolution", "Give an ergometrine-containing uterotonic without checking blood pressure"],
    prescriptionContext: {
      ageYears: 32, weightKg: 70, allergies: [], pregnancyStatus: "not-pregnant",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["postpartum hemorrhage due to uterine atony"],
    },
    prescriptionReference: [
      { genericName: "oxytocin", formulation: "IV infusion", strength: "10-40 units in 500-1000mL", route: "intravenous", frequency: "continuous infusion", duration: "until uterus well contracted, then taper", indication: "First-line uterotonic for atony" },
      { genericName: "carboprost tromethamine", formulation: "IM injection", strength: "250 mcg", route: "intramuscular", frequency: "every 15-90 min, max 8 doses", duration: "until bleeding controlled", indication: "Second-line uterotonic", monitoring: "Avoid in asthma" },
      { genericName: "tranexamic acid", formulation: "IV injection", strength: "1 g", route: "intravenous", frequency: "once, may repeat once", duration: "acute PPH management", indication: "Reduce bleeding-related mortality in PPH" },
    ],
    referenceDx: "Postpartum hemorrhage due to uterine atony",
    viva: [
      { stage: "emergency", prompt: "Walk me through the 4 T's framework for postpartum hemorrhage.", points: ["Tone (atony, most common), Trauma (lacerations), Tissue (retained placenta), Thrombin (coagulopathy)"] },
      { stage: "drug", prompt: "Why must you check blood pressure before giving ergometrine/carboprost?", points: ["Ergometrine risks hypertensive crisis; carboprost is relatively contraindicated in asthma — both need careful patient-specific selection"] },
    ],
    debrief: {
      pearls: ["Uterine atony is the most common cause of PPH — bimanual massage and oxytocin come first, immediately.", "Always systematically check all 4 T's, even once one cause (like atony) is found — trauma can coexist."],
      references: ["WHO Recommendations for the Prevention and Treatment of Postpartum Haemorrhage", "ACOG Practice Bulletin: Postpartum Hemorrhage"],
    },
  },

  {
    slug: "EDU-EM-ANAPHYLAXIS-001",
    title: "Sudden Swelling and Breathlessness After a Meal",
    specialty: "Emergency Medicine",
    difficulty: "FOUNDATION",
    acuity: "EMERGENCY",
    learnerTracks: ["MEDICINE", "NURSING", "PHARMACY"],
    patientSex: "male",
    patientAgeBand: "20-24",
    chiefComplaint: "Sudden facial swelling, hives and breathlessness after eating shellfish",
    learningObjectives: ["Recognize anaphylaxis and its diagnostic criteria", "Know that IM epinephrine is the immediate first-line treatment", "Understand biphasic reaction risk and observation needs"],
    presentation: "A 21-year-old man develops facial swelling, widespread hives, and difficulty breathing within 15 minutes of eating a meal containing shrimp, with no known prior shellfish allergy.",
    initialVitals: { hr: 128, sbp: 84, dbp: 52, rr: 28, spo2: 90, tempC: 37.0, gcs: 15, status: "critical" },
    history: [
      { q: "What did you eat, and when did symptoms start?", category: "presenting-complaint", a: "Shrimp curry, symptoms started within 15 minutes.", key: true },
      { q: "Any known allergies before this?", category: "allergies", a: "None known before today.", key: true },
      { q: "Any throat tightness or difficulty swallowing?", category: "presenting-complaint", a: "Yes, my throat feels tight and it's hard to swallow.", key: true },
      { q: "Any dizziness or feeling like you might faint?", category: "associated-symptoms", a: "Yes, feeling very lightheaded.", key: true },
      { q: "Do you carry an epinephrine auto-injector?", category: "medications", a: "No, never needed one before." },
    ],
    exam: [
      { system: "general", finding: "Diffuse urticaria, facial and lip angioedema.", key: true },
      { system: "respiratory", finding: "Audible stridor, bilateral wheeze, using accessory muscles.", key: true },
      { system: "cardiovascular", finding: "Tachycardic, hypotensive.", key: true },
      { system: "skin", finding: "Widespread erythematous, raised urticarial rash.", key: true },
    ],
    investigations: [
      { name: "Clinical diagnosis (no test should delay treatment)", category: "special", indication: "Anaphylaxis is a clinical diagnosis", turnaround: 0, result: "Meets anaphylaxis criteria: acute onset, skin/mucosal involvement, respiratory compromise, hypotension.", interpretation: "Treat immediately — do not wait for any test.", diagnostic: true },
      { name: "Serum tryptase (if drawn, within 1-2h of onset)", category: "biochemistry", indication: "Retrospective confirmation, not for acute decision-making", turnaround: 240, result: "Elevated (drawn after treatment initiated).", interpretation: "Supports the diagnosis retrospectively; must never delay epinephrine." },
    ],
    redFlags: ["Airway compromise (stridor, throat tightness)", "Hypotension", "Any delay in epinephrine administration increases mortality risk"],
    referenceDifferentials: [
      { diagnosis: "Anaphylaxis (food-triggered)", rationale: "Rapid onset after shellfish ingestion, skin findings, respiratory compromise, hypotension.", mustNotMiss: true },
      { diagnosis: "Acute severe asthma exacerbation", rationale: "Wheeze overlaps, but doesn't explain urticaria/angioedema/hypotension pattern here." },
      { diagnosis: "Vasovagal syncope", rationale: "Would not explain urticaria, angioedema, or bronchospasm." },
    ],
    management: [
      { label: "Give IM epinephrine into the anterolateral thigh IMMEDIATELY", description: "First-line, time-critical treatment for anaphylaxis — do not delay for IV access or other treatments.", critical: true },
      { label: "Call for help / activate emergency response", description: "Anaphylaxis can deteriorate rapidly and may need advanced airway support." , critical: true},
      { label: "Position supine with legs elevated (unless respiratory distress requires sitting up), give high-flow oxygen", description: "Supports circulation and oxygenation." },
      { label: "Give IV fluids for hypotension", description: "Supports blood pressure alongside epinephrine.", critical: true },
      { label: "Give an antihistamine as the first and only treatment", description: "Antihistamines do not treat the life-threatening airway/circulatory components of anaphylaxis — epinephrine must come first.", unsafe: true },
      { label: "Delay epinephrine to first establish IV access and give fluids", description: "Delaying epinephrine for any reason significantly increases mortality risk in anaphylaxis.", unsafe: true },
    ],
    criticalActions: ["Give IM epinephrine into the anterolateral thigh IMMEDIATELY", "Call for help / activate emergency response", "Give IV fluids for hypotension"],
    unsafeActions: ["Give an antihistamine as the first and only treatment", "Delay epinephrine to first establish IV access and give fluids"],
    prescriptionContext: {
      ageYears: 21, weightKg: 74, allergies: ["shellfish (newly identified)"], pregnancyStatus: "not-applicable",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["anaphylaxis"],
    },
    prescriptionReference: [
      { genericName: "epinephrine (adrenaline)", formulation: "IM injection", strength: "0.5 mg (1:1000)", route: "intramuscular", frequency: "repeat every 5-15 min if needed", duration: "acute treatment", indication: "First-line anaphylaxis treatment", monitoring: "Continuous cardiac/BP monitoring, watch for biphasic reaction" },
      { genericName: "chlorpheniramine", formulation: "IV injection", strength: "10 mg", route: "intravenous", frequency: "once", duration: "adjunct only", indication: "Adjunct for urticaria/itch — never a substitute for epinephrine" },
      { genericName: "hydrocortisone", formulation: "IV injection", strength: "200 mg", route: "intravenous", frequency: "once", duration: "adjunct only", indication: "May help prevent biphasic reaction — adjunct, not first-line" },
    ],
    referenceDx: "Anaphylaxis (food-triggered, shellfish)",
    viva: [
      { stage: "emergency", prompt: "What is the single most important immediate treatment for anaphylaxis, and why not start with an antihistamine?", points: ["IM epinephrine — it is the only treatment that reverses the life-threatening airway/circulatory pathophysiology; antihistamines only address skin symptoms"] },
      { stage: "case", prompt: "Why must this patient be observed after apparent recovery?", points: ["Risk of a biphasic anaphylactic reaction hours later"] },
    ],
    debrief: {
      pearls: ["Epinephrine first, always — every other treatment is an adjunct.", "Observe for biphasic reactions; prescribe an epinephrine auto-injector and refer for allergy follow-up on discharge."],
      references: ["World Allergy Organization Anaphylaxis Guidelines"],
    },
  },
];
