import type { CaseDef } from "../builder";

export const surgicalNeuroCases: CaseDef[] = [
  {
    slug: "EDU-SURG-001",
    title: "Migrating Abdominal Pain with Loss of Appetite",
    specialty: "General Surgery",
    difficulty: "FOUNDATION",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "male",
    patientAgeBand: "20-24",
    chiefComplaint: "Abdominal pain that moved from the belly button to the right lower abdomen",
    learningObjectives: ["Recognize classic appendicitis presentation", "Use exam maneuvers (Rovsing, psoas) appropriately", "Understand the surgical urgency of appendicitis"],
    presentation: "A 22-year-old man presents with 18 hours of abdominal pain, initially periumbilical, now localized to the right lower quadrant, with nausea and loss of appetite.",
    initialVitals: { hr: 96, sbp: 122, dbp: 78, rr: 18, spo2: 98, tempC: 38.0, gcs: 15, status: "concern" },
    history: [
      { q: "Where did the pain start, and has it moved?", category: "presenting-complaint", a: "Started around my belly button, now it's moved to the lower right side.", key: true },
      { q: "Any nausea, vomiting or loss of appetite?", category: "associated-symptoms", a: "Yes, lost my appetite completely and vomited once.", key: true },
      { q: "Does anything make the pain worse?", category: "presenting-complaint", a: "Walking and coughing make it worse.", key: true },
      { q: "Any urinary or bowel symptoms?", category: "review-of-systems", a: "Nothing unusual." },
      { q: "Any fever?", category: "associated-symptoms", a: "Felt warm since this morning." },
    ],
    exam: [
      { system: "abdominal", finding: "Maximal tenderness at McBurney's point, with guarding.", key: true },
      { system: "abdominal", finding: "Positive Rovsing's sign (RLQ pain on LLQ palpation).", key: true },
      { system: "abdominal", finding: "Positive psoas sign.", key: true },
      { system: "general", finding: "Low-grade fever, looks unwell.", key: true },
    ],
    investigations: [
      { name: "CBC", category: "hematology", indication: "Suspected appendicitis", turnaround: 30, result: "WBC 14,800/uL, neutrophil predominant.", interpretation: "Supports an acute inflammatory/infective process.", diagnostic: true },
      { name: "Abdominal ultrasound", category: "ultrasound", indication: "Confirm appendicitis, especially in young patients to limit radiation", turnaround: 45, result: "Non-compressible, dilated appendix 9mm with surrounding fat stranding.", interpretation: "Confirms acute appendicitis.", diagnostic: true },
      { name: "CT abdomen/pelvis", category: "ct", indication: "If ultrasound equivocal", turnaround: 60, result: "Not required — ultrasound was already diagnostic.", interpretation: "Reserve for equivocal ultrasound to avoid unnecessary radiation.", distractor: true },
      { name: "Urinalysis", category: "urinalysis", indication: "Exclude urinary tract cause of pain", turnaround: 20, result: "No pyuria, no nitrites.", interpretation: "Helps exclude UTI as an alternative cause." },
    ],
    redFlags: ["Migratory pain pattern is classic and should not be dismissed", "Rebound tenderness suggests possible perforation", "Delay increases risk of perforation/peritonitis"],
    referenceDifferentials: [
      { diagnosis: "Acute appendicitis", rationale: "Classic migratory pain, McBurney's point tenderness, positive Rovsing's/psoas signs, leukocytosis.", mustNotMiss: true },
      { diagnosis: "Right-sided ureteric colic", rationale: "Can mimic appendicitis; excluded by normal urinalysis and ultrasound findings." },
      { diagnosis: "Mesenteric adenitis", rationale: "Consider in younger patients with recent viral illness; less consistent with imaging here." },
    ],
    management: [
      { label: "NPO (nil by mouth) and IV fluids", description: "Prepares for likely surgery and corrects any dehydration.", critical: true },
      { label: "Surgical consultation for appendectomy", description: "Definitive management of acute appendicitis.", critical: true },
      { label: "Empirical IV antibiotics pre-operatively", description: "Reduces post-operative infective complications.", critical: true },
      { label: "Give strong opioid analgesia despite need for serial abdominal exams", description: "Adequate analgesia is appropriate and does not meaningfully obscure surgical decision-making — outdated teaching to withhold analgesia is now considered unsafe practice for the patient.", },
      { label: "Discharge home with oral antibiotics only, no surgical referral", description: "Inadequate for a surgical abdomen with these findings; risks perforation.", unsafe: true },
    ],
    criticalActions: ["NPO (nil by mouth) and IV fluids", "Surgical consultation for appendectomy", "Empirical IV antibiotics pre-operatively"],
    unsafeActions: ["Discharge home with oral antibiotics only, no surgical referral"],
    prescriptionContext: {
      ageYears: 22, weightKg: 72, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["acute appendicitis"],
    },
    prescriptionReference: [
      { genericName: "ceftriaxone", formulation: "IV injection", strength: "1 g", route: "intravenous", frequency: "once", duration: "single pre-operative dose", indication: "Surgical prophylaxis" },
      { genericName: "metronidazole", formulation: "IV injection", strength: "500 mg", route: "intravenous", frequency: "once", duration: "single pre-operative dose", indication: "Anaerobic coverage for surgical prophylaxis" },
    ],
    referenceDx: "Acute appendicitis",
    viva: [
      { stage: "case", prompt: "Why is the migratory nature of this pain diagnostically significant?", points: ["Visceral periumbilical pain from appendiceal distension, then somatic RLQ pain as inflammation reaches the parietal peritoneum"] },
      { stage: "case", prompt: "Why choose ultrasound before CT in this young patient?", points: ["Avoids ionizing radiation in a young patient when ultrasound can be diagnostic"] },
    ],
    debrief: {
      pearls: ["The migratory pain pattern (periumbilical -> RLQ) is one of the most reliable clues in surgical history-taking.", "Adequate analgesia does not obscure the diagnosis and should not be withheld."],
      references: ["World Society of Emergency Surgery Jerusalem Guidelines for Acute Appendicitis"],
    },
  },

  {
    slug: "EDU-SURG-002",
    title: "Right Upper Quadrant Pain After a Fatty Meal",
    specialty: "General Surgery",
    difficulty: "INTERMEDIATE",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "female",
    patientAgeBand: "40-44",
    chiefComplaint: "Right upper abdominal pain and fever after a fatty meal",
    learningObjectives: ["Diagnose acute cholecystitis vs. biliary colic", "Recognize Murphy's sign", "Understand when cholangitis must be considered"],
    presentation: "A 42-year-old woman presents with 12 hours of severe right upper quadrant pain that began after a fatty meal, now with fever, unlike her previous milder episodes.",
    initialVitals: { hr: 100, sbp: 128, dbp: 80, rr: 18, spo2: 98, tempC: 38.6, gcs: 15, status: "concern" },
    history: [
      { q: "Have you had similar pain before?", category: "past-medical", a: "Yes, milder episodes after fatty food, but this is worse and hasn't gone away.", key: true },
      { q: "Any fever or chills?", category: "associated-symptoms", a: "Yes, fever since this morning.", key: true },
      { q: "Any yellowing of your skin or eyes?", category: "review-of-systems", a: "No yellowing." },
      { q: "Any nausea or vomiting?", category: "associated-symptoms", a: "Yes, vomited twice." },
      { q: "Any dark urine or pale stools?", category: "review-of-systems", a: "No, urine and stool look normal.", key: true },
    ],
    exam: [
      { system: "abdominal", finding: "Positive Murphy's sign (inspiratory arrest on RUQ palpation).", key: true },
      { system: "abdominal", finding: "RUQ tenderness with voluntary guarding.", key: true },
      { system: "general", finding: "No jaundice noted.", key: true },
      { system: "general", finding: "Febrile, tachycardic.", key: true },
    ],
    investigations: [
      { name: "Abdominal ultrasound", category: "ultrasound", indication: "Suspected cholecystitis", turnaround: 45, result: "Gallbladder wall thickening (5mm), pericholecystic fluid, multiple gallstones, sonographic Murphy's sign.", interpretation: "Confirms acute cholecystitis.", diagnostic: true },
      { name: "CBC", category: "hematology", indication: "Assess inflammatory response", turnaround: 30, result: "WBC 15,200/uL.", interpretation: "Supports acute inflammatory process." },
      { name: "Liver function tests", category: "biochemistry", indication: "Screen for choledocholithiasis/cholangitis", turnaround: 45, result: "Bilirubin and ALP within normal limits.", interpretation: "Argues against common bile duct obstruction/cholangitis at this time.", diagnostic: true },
      { name: "Lipase/amylase", category: "biochemistry", indication: "Exclude gallstone pancreatitis", turnaround: 40, result: "Normal.", interpretation: "Excludes concurrent pancreatitis." },
    ],
    redFlags: ["Fever + RUQ pain suggests cholecystitis, not simple biliary colic", "Triad of fever, jaundice, RUQ pain would suggest ascending cholangitis (not present here) — a surgical emergency"],
    referenceDifferentials: [
      { diagnosis: "Acute cholecystitis", rationale: "Fever + positive Murphy's sign + ultrasound findings of wall thickening/pericholecystic fluid.", mustNotMiss: true },
      { diagnosis: "Biliary colic", rationale: "Would resolve within hours without fever or sonographic inflammation — this has progressed beyond that." },
      { diagnosis: "Ascending cholangitis", rationale: "Must actively exclude given the consequences of missing it; normal bilirubin/ALP argue against it here.", mustNotMiss: true },
    ],
    management: [
      { label: "NPO, IV fluids, analgesia", description: "Supportive management while arranging definitive care.", critical: true },
      { label: "IV antibiotics covering biliary organisms", description: "Treats the infective component of cholecystitis.", critical: true },
      { label: "Surgical consultation for early laparoscopic cholecystectomy", description: "Early cholecystectomy (within 72h) is preferred over delayed surgery.", critical: true },
      { label: "Discharge with oral antibiotics and outpatient surgical follow-up in 6 weeks", description: "Delayed surgery in confirmed acute cholecystitis increases complication risk versus early cholecystectomy.", unsafe: true },
    ],
    criticalActions: ["NPO, IV fluids, analgesia", "IV antibiotics covering biliary organisms", "Surgical consultation for early laparoscopic cholecystectomy"],
    unsafeActions: ["Discharge with oral antibiotics and outpatient surgical follow-up in 6 weeks"],
    prescriptionContext: {
      ageYears: 42, weightKg: 76, allergies: [], pregnancyStatus: "not-pregnant",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["acute cholecystitis"],
    },
    prescriptionReference: [
      { genericName: "piperacillin-tazobactam", formulation: "IV injection", strength: "4.5 g", route: "intravenous", frequency: "every 8 hours", duration: "until surgery / clinical response", indication: "Biliary sepsis coverage" },
      { genericName: "paracetamol", formulation: "IV injection", strength: "1 g", route: "intravenous", frequency: "QID", duration: "as needed", indication: "Analgesia" },
    ],
    referenceDx: "Acute cholecystitis",
    viva: [
      { stage: "case", prompt: "What distinguishes acute cholecystitis from simple biliary colic?", points: ["Fever, sustained (not resolving) pain, sonographic wall thickening/pericholecystic fluid, positive Murphy's sign"] },
      { stage: "case", prompt: "What triad would make you worry about ascending cholangitis instead?", points: ["Charcot's triad: fever, jaundice, RUQ pain"] },
    ],
    debrief: {
      pearls: ["Early laparoscopic cholecystectomy (within 72h) is now preferred over delayed surgery for acute cholecystitis.", "Always screen LFTs to exclude concurrent common bile duct obstruction/cholangitis."],
      references: ["Tokyo Guidelines for Acute Cholecystitis and Cholangitis"],
    },
  },

  {
    slug: "EDU-NEURO-001",
    title: "Sudden Facial Droop and Arm Weakness",
    specialty: "Neurology",
    difficulty: "INTERMEDIATE",
    acuity: "EMERGENCY",
    learnerTracks: ["MEDICINE", "NURSING", "PHYSIOTHERAPY"],
    patientSex: "male",
    patientAgeBand: "65-69",
    chiefComplaint: "Sudden facial droop, slurred speech and left arm weakness",
    learningObjectives: ["Apply FAST criteria and NIHSS concepts", "Determine thrombolysis eligibility by time window", "Identify stroke mimics and contraindications to tPA"],
    presentation: "A 67-year-old man was last seen normal 90 minutes ago and was then found by his wife with facial droop, slurred speech, and left arm weakness.",
    initialVitals: { hr: 88, sbp: 168, dbp: 96, rr: 18, spo2: 97, tempC: 36.9, gcs: 14, status: "concern" },
    history: [
      { q: "When was he last known to be normal?", category: "presenting-complaint", a: "90 minutes ago, his wife spoke to him then.", key: true },
      { q: "Any head trauma or recent surgery?", category: "past-medical", a: "No recent trauma or surgery.", key: true },
      { q: "Is he on any blood thinners?", category: "medications", a: "No anticoagulants, just aspirin." , key: true},
      { q: "Any history of seizures?", category: "past-medical", a: "No seizure history." },
      { q: "Does he have atrial fibrillation or heart disease?", category: "past-medical", a: "Yes, known atrial fibrillation, not on anticoagulation currently.", key: true },
    ],
    exam: [
      { system: "neurological", finding: "Right facial droop, left arm drift, left-sided weakness (3/5), dysarthria.", key: true },
      { system: "neurological", finding: "NIHSS estimated at 9.", key: true },
      { system: "cardiovascular", finding: "Irregularly irregular pulse consistent with atrial fibrillation.", key: true },
      { system: "mental-status", finding: "Alert, oriented, GCS 14 (dysarthria only affecting verbal score)." },
    ],
    investigations: [
      { name: "Non-contrast CT head", category: "ct", indication: "Exclude hemorrhage before thrombolysis", turnaround: 20, result: "No acute hemorrhage, early ischemic changes in right MCA territory.", interpretation: "No hemorrhage — thrombolysis not contraindicated on this basis.", diagnostic: true },
      { name: "Blood glucose", category: "biochemistry", indication: "Exclude hypoglycemia as a stroke mimic", turnaround: 2, result: "104 mg/dL.", interpretation: "Normal — excludes hypoglycemia as the cause.", diagnostic: true },
      { name: "ECG", category: "ecg", indication: "Confirm atrial fibrillation as embolic source", turnaround: 5, result: "Atrial fibrillation, no acute ischemic changes.", interpretation: "Likely cardioembolic source for stroke.", diagnostic: true },
      { name: "Coagulation panel (PT/INR, aPTT)", category: "special", indication: "Confirm not anticoagulated before thrombolysis", turnaround: 30, result: "INR 1.0, aPTT normal.", interpretation: "Not anticoagulated — supports thrombolysis eligibility." },
    ],
    redFlags: ["Within thrombolysis window but window closing", "Atrial fibrillation as embolic source", "Elevated BP needs control before thrombolysis"],
    referenceDifferentials: [
      { diagnosis: "Acute ischemic stroke (cardioembolic, right MCA territory)", rationale: "Sudden focal neuro deficit, CT excludes hemorrhage, known AF as embolic source.", mustNotMiss: true },
      { diagnosis: "Hemorrhagic stroke", rationale: "Excluded by non-contrast CT." },
      { diagnosis: "Hypoglycemia (stroke mimic)", rationale: "Excluded by normal glucose." },
    ],
    management: [
      { label: "Confirm time last known well and calculate thrombolysis window", description: "Determines eligibility for time-critical reperfusion therapy.", critical: true },
      { label: "Non-contrast CT head to exclude hemorrhage before any thrombolytic", description: "Mandatory before tPA.", critical: true },
      { label: "Give IV thrombolysis (alteplase) if within window and no contraindication", description: "Time-critical reperfusion therapy for eligible ischemic stroke.", critical: true },
      { label: "Aggressively lower BP to <120/80 immediately with IV agents", description: "Overly aggressive BP lowering can worsen cerebral perfusion in acute stroke; specific, cautious targets apply only when giving thrombolysis.", unsafe: true },
      { label: "Give aspirin immediately alongside thrombolysis", description: "Antiplatelets are typically withheld for 24h after thrombolysis due to bleeding risk.", unsafe: true },
    ],
    criticalActions: ["Confirm time last known well and calculate thrombolysis window", "Non-contrast CT head to exclude hemorrhage before any thrombolytic", "Give IV thrombolysis (alteplase) if within window and no contraindication"],
    unsafeActions: ["Aggressively lower BP to <120/80 immediately with IV agents", "Give aspirin immediately alongside thrombolysis"],
    prescriptionContext: {
      ageYears: 67, weightKg: 80, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: ["aspirin"], diagnoses: ["acute ischemic stroke"],
    },
    prescriptionReference: [
      { genericName: "alteplase", formulation: "IV infusion", strength: "0.9 mg/kg (max 90mg), 10% bolus then infusion over 60 min", route: "intravenous", frequency: "once", duration: "single treatment course", indication: "Thrombolysis for acute ischemic stroke within window", monitoring: "Neuro checks, BP <180/105 during and after infusion" },
      { genericName: "aspirin", formulation: "tablet", strength: "300 mg", route: "oral", frequency: "once daily starting 24h post-thrombolysis", duration: "ongoing", indication: "Secondary stroke prevention" },
    ],
    referenceDx: "Acute ischemic stroke, cardioembolic (right MCA territory)",
    viva: [
      { stage: "emergency", prompt: "What must you exclude on CT before giving thrombolysis, and why?", points: ["Intracranial hemorrhage — thrombolysis would be catastrophic if hemorrhage present"] },
      { stage: "case", prompt: "Why not give aspirin at the same time as alteplase?", points: ["Combined bleeding risk — aspirin typically deferred ~24h post-thrombolysis"] },
    ],
    debrief: {
      pearls: ["'Time is brain' — every step from arrival to needle should be timed and minimized.", "Hypoglycemia is a classic, easily reversible stroke mimic — always check glucose."],
      references: ["AHA/ASA Guidelines for Early Management of Acute Ischemic Stroke"],
    },
  },

  {
    slug: "EDU-NEURO-002",
    title: "Witnessed Convulsion in a Young Man",
    specialty: "Neurology",
    difficulty: "INTERMEDIATE",
    acuity: "EMERGENCY",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "male",
    patientAgeBand: "25-29",
    chiefComplaint: "Witnessed generalized convulsion, now ongoing 8 minutes",
    learningObjectives: ["Apply status epilepticus stepwise drug protocol", "Identify reversible causes of seizure (glucose, electrolytes)", "Manage airway during active seizure safely"],
    presentation: "A 27-year-old man with known epilepsy is having a witnessed generalized tonic-clonic seizure that has now continued for 8 minutes without stopping.",
    initialVitals: { hr: 132, sbp: 148, dbp: 92, rr: 8, spo2: 84, tempC: 37.4, gcs: 3, status: "critical" },
    history: [
      { q: "Has he had any medication changes recently?", category: "medications", a: "Family says he ran out of his levetiracetam 3 days ago.", key: true },
      { q: "Any alcohol or recreational drug use?", category: "social", a: "Family denies any known use." },
      { q: "Any recent head injury or fever?", category: "past-medical", a: "No injury, no fever reported before this." },
      { q: "How long has the seizure been going on?", category: "presenting-complaint", a: "About 8 minutes continuously per witnesses.", key: true },
    ],
    exam: [
      { system: "neurological", finding: "Ongoing generalized tonic-clonic movements, unresponsive.", key: true },
      { system: "respiratory", finding: "Cyanosis, inadequate respiratory effort, SpO2 84%.", key: true },
      { system: "general", finding: "Tongue biting noted, no signs of trauma elsewhere." },
    ],
    investigations: [
      { name: "Point-of-care glucose", category: "biochemistry", indication: "Exclude hypoglycemic seizure", turnaround: 1, result: "98 mg/dL.", interpretation: "Normal — excludes hypoglycemia as the cause.", diagnostic: true },
      { name: "Serum electrolytes (including sodium, calcium, magnesium)", category: "biochemistry", indication: "Exclude metabolic causes", turnaround: 30, result: "Within normal limits.", interpretation: "No metabolic precipitant identified." },
      { name: "Anti-epileptic drug level (levetiracetam)", category: "biochemistry", indication: "Assess adherence", turnaround: 90, result: "Undetectable.", interpretation: "Confirms medication non-adherence as the likely precipitant.", diagnostic: true },
      { name: "CT head", category: "ct", indication: "First seizure or focal features / not returning to baseline", turnaround: 30, result: "Not urgently indicated given known epilepsy and clear precipitant, but reasonable once stabilized.", interpretation: "Lower priority than airway/seizure termination in this moment.", distractor: true },
    ],
    redFlags: ["Seizure >5 minutes = status epilepticus, treat immediately", "Hypoxia during ongoing convulsion", "GCS 3 requiring airway protection"],
    referenceDifferentials: [
      { diagnosis: "Status epilepticus secondary to anti-epileptic non-adherence", rationale: "Known epileptic, missed levetiracetam, ongoing seizure >5 min, undetectable drug level.", mustNotMiss: true },
      { diagnosis: "Hypoglycemic seizure", rationale: "Excluded by normal glucose." },
      { diagnosis: "Structural intracranial lesion (new)", rationale: "Consider once stabilized, especially if not returning to baseline promptly.", mustNotMiss: true },
    ],
    management: [
      { label: "Protect airway, position on side, high-flow oxygen", description: "First priority — ABC before drug therapy.", critical: true },
      { label: "Check glucose immediately", description: "Rapid reversible cause to exclude.", critical: true },
      { label: "Give IV/IM benzodiazepine (e.g. lorazepam) as first-line", description: "First-line abortive therapy for status epilepticus.", critical: true },
      { label: "If seizure continues, load with second-line agent (e.g. IV levetiracetam or fosphenytoin)", description: "Second-line therapy per status epilepticus protocol.", critical: true },
      { label: "Attempt to forcibly restrain limbs to 'stop the shaking'", description: "Risk of injury and does not terminate the seizure — never restrain limbs during a convulsion.", unsafe: true },
      { label: "Insert a hard object into the mouth to prevent tongue biting", description: "Outdated and dangerous — risks airway obstruction and dental/oral injury.", unsafe: true },
    ],
    criticalActions: ["Protect airway, position on side, high-flow oxygen", "Check glucose immediately", "Give IV/IM benzodiazepine (e.g. lorazepam) as first-line"],
    unsafeActions: ["Attempt to forcibly restrain limbs to 'stop the shaking'", "Insert a hard object into the mouth to prevent tongue biting"],
    prescriptionContext: {
      ageYears: 27, weightKg: 74, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: ["levetiracetam (lapsed)"], diagnoses: ["status epilepticus"],
    },
    prescriptionReference: [
      { genericName: "lorazepam", formulation: "IV injection", strength: "4 mg", route: "intravenous", frequency: "once, may repeat once after 5-10 min", duration: "acute abortive therapy", indication: "First-line status epilepticus treatment" },
      { genericName: "levetiracetam", formulation: "IV infusion", strength: "60 mg/kg (max 4.5g)", route: "intravenous", frequency: "loading dose once", duration: "then resume oral maintenance", indication: "Second-line status epilepticus therapy / maintenance restart" },
    ],
    referenceDx: "Status epilepticus secondary to anti-epileptic medication non-adherence",
    viva: [
      { stage: "emergency", prompt: "At what time point does a seizure become 'status epilepticus' requiring treatment escalation?", points: ["5 minutes of continuous seizure, or recurrent seizures without return to baseline"] },
      { stage: "emergency", prompt: "Why is inserting an object in the mouth during a seizure dangerous and outdated?", points: ["Airway obstruction risk, dental/oral trauma, no proven benefit"] },
    ],
    debrief: {
      pearls: ["Medication non-adherence is one of the most common precipitants of breakthrough seizures.", "Airway and glucose come before anti-epileptic drug therapy in the initial seconds of management."],
      references: ["AES/ACEP Status Epilepticus Treatment Guideline"],
    },
  },

  {
    slug: "EDU-NEURO-003",
    title: "Severe Headache, Neck Stiffness and Fever",
    specialty: "Neurology",
    subspecialty: "Infectious Disease",
    difficulty: "ADVANCED",
    acuity: "EMERGENCY",
    learnerTracks: ["MEDICINE", "NURSING"],
    patientSex: "female",
    patientAgeBand: "18-24",
    chiefComplaint: "Severe headache, neck stiffness, fever and photophobia",
    learningObjectives: ["Recognize meningitis and its red flags", "Understand when to image before lumbar puncture", "Know empirical antibiotic timing in suspected bacterial meningitis"],
    presentation: "A 19-year-old university student presents with 12 hours of severe headache, high fever, neck stiffness, and photophobia. Her roommate reports she seemed confused this morning.",
    initialVitals: { hr: 116, sbp: 100, dbp: 62, rr: 22, spo2: 96, tempC: 39.8, gcs: 13, status: "critical" },
    history: [
      { q: "How would you describe the headache?", category: "presenting-complaint", a: "Worst headache of my life, constant, all over.", key: true },
      { q: "Any sensitivity to light?", category: "associated-symptoms", a: "Yes, light really hurts my eyes.", key: true },
      { q: "Any rash?", category: "review-of-systems", a: "Roommate noticed some small purple spots on her legs this morning.", key: true },
      { q: "Any recent illness or living in close quarters (dorms)?", category: "social", a: "Lives in a university dormitory, no recent illness.", key: true },
      { q: "Any neck stiffness?", category: "presenting-complaint", a: "Yes, can't touch chin to chest." , key: true},
    ],
    exam: [
      { system: "neurological", finding: "Nuchal rigidity, positive Kernig's and Brudzinski's signs.", key: true },
      { system: "skin", finding: "Non-blanching petechial rash on lower limbs.", key: true },
      { system: "mental-status", finding: "Confused, GCS 13.", key: true },
      { system: "general", finding: "High fever, photophobia on exam." },
    ],
    investigations: [
      { name: "Blood cultures", category: "microbiology", indication: "Before antibiotics, without delaying treatment", turnaround: 2880, result: "Pending; grew Neisseria meningitidis at 24h.", interpretation: "Confirms bacterial meningococcal etiology." },
      { name: "Lumbar puncture / CSF analysis", category: "special", indication: "Confirm meningitis, guide therapy", turnaround: 90, result: "Turbid CSF, WBC 2400/uL (neutrophil predominant), glucose low, protein high.", interpretation: "Classic bacterial meningitis CSF pattern.", diagnostic: true },
      { name: "CT head (before LP, given GCS 13/confusion)", category: "ct", indication: "Exclude raised ICP before lumbar puncture given altered mentation", turnaround: 30, result: "No mass lesion, no midline shift, no signs of raised ICP.", interpretation: "Safe to proceed with LP.", diagnostic: true },
      { name: "CBC", category: "hematology", indication: "Assess systemic infection/DIC risk given petechiae", turnaround: 30, result: "WBC 22,000/uL, platelets 88,000/uL (low).", interpretation: "Supports severe bacterial sepsis with early coagulopathy — meningococcemia." },
    ],
    redFlags: ["Non-blanching petechial rash = meningococcemia until proven otherwise", "Altered mental status", "Do NOT delay antibiotics for CT/LP"],
    referenceDifferentials: [
      { diagnosis: "Bacterial meningitis (meningococcal)", rationale: "Classic triad (fever, neck stiffness, altered mental status) plus non-blanching rash and CSF findings.", mustNotMiss: true },
      { diagnosis: "Viral meningitis", rationale: "Usually less severe, CSF lymphocyte-predominant with normal glucose — doesn't fit this CSF picture." },
      { diagnosis: "Subarachnoid hemorrhage", rationale: "'Worst headache of life' overlaps, but the rash and CSF/fever pattern here support infection.", mustNotMiss: true },
    ],
    management: [
      { label: "Give empirical IV antibiotics IMMEDIATELY, before any imaging or LP", description: "Antibiotic delay is the single most important preventable cause of death in bacterial meningitis.", critical: true },
      { label: "Give IV dexamethasone with or just before first antibiotic dose", description: "Reduces neurological complications in bacterial meningitis when given early.", critical: true },
      { label: "Droplet/respiratory isolation precautions", description: "Meningococcal disease is transmissible; protects staff and other patients.", critical: true },
      { label: "Delay antibiotics until after CT head and lumbar puncture results are back", description: "Dangerous delay — antibiotics must be given immediately on clinical suspicion, imaging/LP can follow.", unsafe: true },
      { label: "Perform lumbar puncture immediately without considering raised ICP risk given GCS 13", description: "Risk of coning if raised intracranial pressure is present and unrecognized — CT first is appropriate given altered mentation, but this must never delay antibiotics.", unsafe: true },
    ],
    criticalActions: ["Give empirical IV antibiotics IMMEDIATELY, before any imaging or LP", "Give IV dexamethasone with or just before first antibiotic dose", "Droplet/respiratory isolation precautions"],
    unsafeActions: ["Delay antibiotics until after CT head and lumbar puncture results are back", "Perform lumbar puncture immediately without considering raised ICP risk given GCS 13"],
    prescriptionContext: {
      ageYears: 19, weightKg: 58, allergies: [], pregnancyStatus: "not-pregnant",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["bacterial meningitis (meningococcal)"],
    },
    prescriptionReference: [
      { genericName: "ceftriaxone", formulation: "IV injection", strength: "2 g", route: "intravenous", frequency: "every 12 hours", duration: "7-10 days", indication: "Empirical bacterial meningitis coverage" },
      { genericName: "dexamethasone", formulation: "IV injection", strength: "10 mg", route: "intravenous", frequency: "every 6 hours", duration: "4 days", indication: "Reduce neurological complications", monitoring: "Given with or just before first antibiotic dose" },
    ],
    referenceDx: "Bacterial meningitis with meningococcemia",
    viva: [
      { stage: "emergency", prompt: "What is the single most important management priority once bacterial meningitis is suspected?", points: ["Immediate empirical antibiotics — do not wait for CT, LP, or culture results"] },
      { stage: "case", prompt: "Why get a CT head before LP in this specific patient?", points: ["Altered mental status/confusion raises concern for raised ICP, where LP risks coning; CT screens for mass effect first — but must not delay antibiotics"] },
    ],
    debrief: {
      pearls: ["Antibiotics for suspected bacterial meningitis should never wait for imaging, LP, or culture confirmation.", "A non-blanching petechial rash with fever is meningococcemia until proven otherwise."],
      references: ["IDSA Practice Guidelines for Bacterial Meningitis"],
    },
  },

  {
    slug: "EDU-ORTHO-001",
    title: "Fall From a Ladder With Deformed, Painful Forearm",
    specialty: "Orthopedics",
    difficulty: "FOUNDATION",
    acuity: "URGENT",
    learnerTracks: ["MEDICINE", "NURSING", "PHYSIOTHERAPY"],
    patientSex: "male",
    patientAgeBand: "35-39",
    chiefComplaint: "Painful, deformed right forearm after a fall from a ladder",
    learningObjectives: ["Assess for neurovascular compromise in fractures", "Recognize compartment syndrome red flags", "Understand basic fracture immobilization principles"],
    presentation: "A 37-year-old man presents after falling approximately 2 meters from a ladder, landing on his outstretched right arm, with immediate pain and visible deformity of the forearm.",
    initialVitals: { hr: 104, sbp: 138, dbp: 84, rr: 18, spo2: 98, tempC: 37.0, gcs: 15, status: "concern" },
    history: [
      { q: "How did you land?", category: "presenting-complaint", a: "Landed on my outstretched right hand and arm.", key: true },
      { q: "Any numbness or tingling in your hand?", category: "presenting-complaint", a: "Yes, my fingers feel a bit numb.", key: true },
      { q: "Any other injuries — head, neck, back?", category: "presenting-complaint", a: "No, just the arm, I didn't hit my head." },
      { q: "How severe is the pain, and is it getting worse?", category: "presenting-complaint", a: "Severe, and it feels like it's getting worse, out of proportion to what I'd expect.", key: true },
      { q: "Any previous fractures or bone conditions?", category: "past-medical", a: "No, first fracture." },
    ],
    exam: [
      { system: "musculoskeletal", finding: "Visible deformity of mid-forearm, swelling, unable to move wrist/fingers fully.", key: true },
      { system: "musculoskeletal", finding: "Pain on passive stretch of fingers, tense forearm compartments.", key: true },
      { system: "musculoskeletal", finding: "Reduced sensation in median nerve distribution, radial pulse present but weak.", key: true },
      { system: "general", finding: "No head/neck/chest/abdominal injury on primary survey." },
    ],
    investigations: [
      { name: "Forearm X-ray (AP and lateral)", category: "xray", indication: "Confirm fracture pattern", turnaround: 20, result: "Displaced fracture of both radius and ulna shafts.", interpretation: "Confirms both-bone forearm fracture.", diagnostic: true },
      { name: "Compartment pressure measurement (if available)", category: "special", indication: "Suspected compartment syndrome", turnaround: 15, result: "Elevated compartment pressure, >30 mmHg.", interpretation: "Confirms compartment syndrome — surgical emergency.", diagnostic: true },
      { name: "CBC and coagulation panel", category: "hematology", indication: "Pre-operative baseline", turnaround: 30, result: "Within normal limits.", interpretation: "No contraindication to urgent surgery identified." },
    ],
    redFlags: ["Pain out of proportion to injury = compartment syndrome until excluded", "Pain on passive stretch is an early, sensitive sign", "Neurovascular compromise requires urgent reassessment"],
    referenceDifferentials: [
      { diagnosis: "Both-bone forearm fracture with acute compartment syndrome", rationale: "Deformity + fracture on X-ray + pain out of proportion + pain on passive stretch + elevated compartment pressure.", mustNotMiss: true },
      { diagnosis: "Simple forearm fracture without compartment syndrome", rationale: "Excluded once compartment pressure/exam confirms compartment syndrome." },
      { diagnosis: "Nerve injury alone (without fracture)", rationale: "X-ray confirms an underlying fracture is also present." },
    ],
    management: [
      { label: "Neurovascular assessment before and after any splinting", description: "Detects and tracks evolving compromise.", critical: true },
      { label: "Urgent orthopedic surgery consultation for emergency fasciotomy", description: "Compartment syndrome is a limb-threatening surgical emergency.", critical: true },
      { label: "Elevate limb to heart level (not above) and avoid tight circumferential dressings/casts", description: "Correct positioning; elevating above heart level can worsen perfusion in compartment syndrome." },
      { label: "Apply a tight, fully circumferential cast immediately for 'stability'", description: "Can worsen compartment syndrome by further raising compartment pressure.", unsafe: true },
      { label: "Elevate the limb well above heart level to 'reduce swelling'", description: "Excessive elevation can reduce arterial perfusion pressure and worsen ischemia in compartment syndrome.", unsafe: true },
    ],
    criticalActions: ["Neurovascular assessment before and after any splinting", "Urgent orthopedic surgery consultation for emergency fasciotomy"],
    unsafeActions: ["Apply a tight, fully circumferential cast immediately for 'stability'", "Elevate the limb well above heart level to 'reduce swelling'"],
    prescriptionContext: {
      ageYears: 37, weightKg: 80, allergies: [], pregnancyStatus: "not-applicable",
      renalFunction: "normal", hepaticFunction: "normal", currentMedications: [], diagnoses: ["both-bone forearm fracture", "acute compartment syndrome"],
    },
    prescriptionReference: [
      { genericName: "morphine", formulation: "IV injection", strength: "0.1 mg/kg titrated", route: "intravenous", frequency: "PRN, titrate to pain", duration: "peri-operative", indication: "Analgesia — note worsening pain despite adequate analgesia is itself a compartment syndrome red flag" },
      { genericName: "cefazolin", formulation: "IV injection", strength: "2 g", route: "intravenous", frequency: "pre-operative dose", duration: "surgical prophylaxis", indication: "Prophylaxis before fasciotomy/fixation" },
    ],
    referenceDx: "Both-bone forearm fracture with acute compartment syndrome",
    viva: [
      { stage: "emergency", prompt: "What clinical sign is most sensitive for early compartment syndrome?", points: ["Pain out of proportion to injury and pain on passive stretch of the muscles involved"] },
      { stage: "case", prompt: "Why is compartment syndrome a surgical emergency even before pulses are lost?", points: ["Pulselessness is a very late sign — irreversible muscle/nerve damage can occur before pulses are affected"] },
    ],
    debrief: {
      pearls: ["Pain out of proportion to the injury, worsening despite analgesia, is the single most important early clue to compartment syndrome.", "Do not wait for pulselessness — it is a late and unreliable sign."],
      references: ["OTA/AAOS Clinical Practice Guideline on Acute Compartment Syndrome"],
    },
  },
];
